


INSERT INTO `SERIOUSNESS` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `IMPACT`, `LIKELIHOOD`, `SERIOUSNESS`) VALUES
(1, 1, 1, 1, 1, 1),
(2, 1, 1, 2, 1, 1),
(3, 1, 1, 3, 1, 2),
(4, 1, 1, 4, 1, 2),
(5, 1, 1, 1, 2, 1),
(6, 1, 1, 2, 2, 2),
(7, 1, 1, 3, 2, 3),
(8, 1, 1, 4, 2, 3),
(9, 1, 1, 1, 3, 1),
(10, 1, 1, 2, 3, 2),
(11, 1, 1, 3, 3, 3),
(12, 1, 1, 4, 3, 4),
(13, 1, 1, 1, 4, 2),
(14, 1, 1, 2, 4, 3),
(15, 1, 1, 3, 4, 4),
(16, 1, 1, 4, 4, 4);



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '1', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '2', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '3', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '1', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '2', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '3', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '1', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '2', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '3', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Availability', '4', '4', '1');







INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '1', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '2', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '4', '1', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '1', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '2', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '4', '2', '2');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '3', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Availability', '4', '4', '1');









INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '1', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '2', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '3', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '4', '1', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '1', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '2', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '4', '2', '2');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '3', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Availability', '4', '4', '1');










INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '1', '1', '4');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '2', '1', '4');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '3', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '4', '1', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '1', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '2', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '3', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '4', '2', '2');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '3', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '4', '3', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Availability', '4', '4', '1');




INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '1', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '2', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '3', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '1', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '2', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '3', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '1', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '2', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '3', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Integrity', '4', '4', '1');







INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '1', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '2', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '1', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '2', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '3', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Integrity', '4', '4', '1');









INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '1', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '2', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '1', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '2', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '3', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Integrity', '4', '4', '1');










INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '1', '1', '4');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '2', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '1', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '2', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '3', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Integrity', '4', '4', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '1', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '2', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '3', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '1', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '2', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '3', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '1', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '2', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '3', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Confidentiality', '4', '4', '1');







INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '1', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '2', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '4', '1', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '1', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '2', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '4', '2', '2');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '3', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '4', '3', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '1', '4', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '2', '4', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '3', '4', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Confidentiality', '4', '4', '2');









INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '1', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '2', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '4', '1', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '1', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '2', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '4', '2', '2');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '1', '3', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '2', '3', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '3', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '4', '3', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '1', '4', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '2', '4', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '3', '4', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Confidentiality', '4', '4', '2');










INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '1', '1', '4');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '2', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '4', '1', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '1', '2', '4');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '2', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '4', '2', '2');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '1', '3', '4');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '2', '3', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '3', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '4', '3', '2');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '1', '4', '4');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '2', '4', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '3', '4', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Confidentiality', '4', '4', '2');








INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '1', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '2', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '3', '1', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '1', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '2', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '3', '2', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '1', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '2', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '3', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '1', 'Efficiency', '4', '4', '1');







INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '1', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '2', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '1', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '2', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '3', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '2', 'Efficiency', '4', '4', '1');









INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '1', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '2', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '1', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '2', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '3', '3', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '3', 'Efficiency', '4', '4', '1');










INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '1', '1', '4');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '2', '1', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '3', '1', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '4', '1', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '1', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '2', '2', '3');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '3', '2', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '4', '2', '1');



INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '1', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '2', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '3', '3', '2');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '4', '3', '1');


INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '1', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '2', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '3', '4', '1');

INSERT INTO `STATUS_IMPACT` (`PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_IMPACT`, `SECURITY_IMPACT`, `CONFINING`, `PALLIATION`, `CALCULATED_IMPACT`) VALUES ('1', '1', '4', 'Efficiency', '4', '4', '1');








INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '1', '1', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '2', '1', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '3', '1', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '4', '1', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '1', '2', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '2', '2', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '3', '2', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '4', '2', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '1', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '2', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '3', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '4', '3', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Accidental', '4', '4', '1');






INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '1', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '2', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '3', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '4', '1', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '1', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '2', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '3', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '4', '2', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '1', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '2', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '3', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '4', '3', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Accidental', '4', '4', '1');





INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '1', '1', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '2', '1', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '3', '1', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '4', '1', '3');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '1', '2', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '2', '2', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '3', '2', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '4', '2', '3');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '1', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '2', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '3', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '4', '3', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Accidental', '4', '4', '1');







INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '1', '1', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '2', '1', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '3', '1', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '4', '1', '4');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '1', '2', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '2', '2', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '3', '2', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '4', '2', '4');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '1', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '2', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '3', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '4', '3', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Accidental', '4', '4', '1');










INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '1', '1', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '2', '1', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '3', '1', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '4', '1', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '1', '2', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '2', '2', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '3', '2', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '4', '2', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '1', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '2', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '3', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '4', '3', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Error', '4', '4', '1');






INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '1', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '2', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '3', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '4', '1', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '1', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '2', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '3', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '4', '2', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '1', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '2', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '3', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '4', '3', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Error', '4', '4', '1');





INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '1', '1', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '2', '1', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '3', '1', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '4', '1', '3');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '1', '2', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '2', '2', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '3', '2', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '4', '2', '3');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '1', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '2', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '3', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '4', '3', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Error', '4', '4', '1');







INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '1', '1', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '2', '1', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '3', '1', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '4', '1', '4');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '1', '2', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '2', '2', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '3', '2', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '4', '2', '4');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '1', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '2', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '3', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '4', '3', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Error', '4', '4', '1');















INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '1', '1', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '2', '1', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '3', '1', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '4', '1', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '1', '2', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '2', '2', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '3', '2', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '4', '2', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '1', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '2', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '3', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '4', '3', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '1', 'Deliberate', '4', '4', '1');






INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '1', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '2', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '3', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '4', '1', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '1', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '2', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '3', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '4', '2', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '1', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '2', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '3', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '4', '3', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '2', 'Deliberate', '4', '4', '1');





INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '1', '1', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '2', '1', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '3', '1', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '4', '1', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '1', '2', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '2', '2', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '3', '2', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '4', '2', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '1', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '2', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '3', '3', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '4', '3', '1');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '1', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '2', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '3', '4', '1');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '3', 'Deliberate', '4', '4', '1');







INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '1', '1', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '2', '1', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '3', '1', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '4', '1', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '1', '2', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '2', '2', '4');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '3', '2', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '4', '2', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '1', '3', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '2', '3', '3');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '3', '3', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '4', '3', '2');


INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '1', '4', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '2', '4', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '3', '4', '2');

INSERT INTO `STATUS_LIKELIHOOD` (`ID`, `PROJECT_ID`, `PROFILE_ID`, `INTRINSIC_LIKELIHOOD`, `CLASS`, `DISSUASION`, `PREVENTION`, `CALCULATED_LIKELIHOOD`) VALUES (NULL, '1', '1', '4', 'Deliberate', '4', '4', '1');


