ALTER TABLE `ROLE`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `ASSPROCEDURE`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `QUESTIONNAIRE_MODEL`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `SECREQUIREMENT_SAFEGUARD`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `SECREQUIREMENT_REFERENCE`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `ASSAUDIT`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `SERIOUSNESS`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `ASSPROJECT`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `ASSPROFILE_TEMPLATE`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `ASSPROFILE`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `ASSTEMPLATE`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `SESTUSER_PSW`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `SESTUSER`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `REQUIREMENT`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `SYSPARTICIPANT`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `SYSPROJECT`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `ASSET_MODEL`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `VULNERABILITY_MODEL`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `VULNERABILITY_REFERENCE`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `VULNERABILITY_ASSET_REFERENCE`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `RISK_MODEL`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `THREAT_MODEL`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `RISK_SCENARIO_REFERENCE`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `SAFEGUARD_MODEL`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `STATUS_IMPACT`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `STATUS_LIKELIHOOD`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `RISKTREATMENT_MODEL`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `SESTOBJ`
ENCRYPTED=YES encryption_key_id=1;
ALTER TABLE `ASSAUDIT_DEFAULT`
ENCRYPTED=YES encryption_key_id=1;
