INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2019,'12','QUESTIONNAIRE','MEHARI_TelecommunicationOperation','12','','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2020,'12','CATEGORY','Security of operational procedures ','12A','12','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2021,'01','CATEGORY','Consideration of security in relation with operational personnel (permanent and temporary staff)','12A01','12A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2022,'01','QUESTION','Is there a security policy, specifically aimed at operations personnel, related to telecommunications?
This policy should cover the requirements for the protection of information as well as the protection of physical assets and processes and mention the forbidden behaviors','12A01-01','12A01','4','','','E1','11.2.1','9.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2023,'02','QUESTION','Is telecommunication operations personnel required to sign contract clauses of adherence to that security policy (no matter their status: permanent or temporary staff, students, etc.)?','12A01-02','12A01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2024,'03','QUESTION','Do these clauses make clear that the personnel has an obligation not to tolerate any action contrary to security from other people?','12A01-03','12A01','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2025,'04','QUESTION','Does the signature of these clauses represent a formal commitment?
In order to achieve a formal commitment, the personnel should explicitly state that his/her signature implies having understood and accepted the security policy','12A01-04','12A01','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2026,'05','QUESTION','Are these same clauses obligatory for contractors working on systems operations?
Practically, the contractors should ensure that their personnel sign individually and explicitly under the same conditions than internal staff. ','12A01-05','12A01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2027,'06','QUESTION','Is there a mandatory and well adapted training course aimed at systems operation personnel?','12A01-06','12A01','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2028,'07','QUESTION','Are the security policy compliance agreements, signed by personnel, securely kept (at least in a locked cupboard )?  ','12A01-07','12A01','2','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2029,'08','QUESTION','Are the security policy compliance agreements, signed by external contractors, securely kept (at least in a locked cupboard )?  ','12A01-08','12A01','2','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2030,'09','QUESTION','Is there a regular audit, at least once a year, of the effective application of the signature procedure by  operational personnel (directly employed by the company or indirectly through a service company)?  ','12A01-09','12A01','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2031,'02','CATEGORY','Control of the implementation of new equipment or upgrade of existing systems
Equipment for classical telephony: PABX,
With VoIP: call server, gateway converter to classical telephony, routers, switches
Equipment dedicated to users: telephone terminal, fax machines (often combined with printing, scanning and photocopy capabilities, ...), tele and videoconferencing,
These systems may provide configuration, management, directory, billing and storage (answering machine, voice mail) services','12A02','12A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2032,'01','QUESTION','Are the decisions to change or update equipment and systems significantly subject to a control procedure (registration, planning, formal approval, communication to all concerned individuals, etc.)?
The possible separation (physical or logical, using VLAN) of data and voice flows shall be analyzed when moving to VoIP and revised based on the observed load changes, the same applies to interconnection capabilities between the two networks ','12A02-01','12A02','4','','','E1','12.1.2; 12.1.3','10.1.2; 10.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2033,'02','QUESTION','Are the change decisions based on an analysis of the capacity of the new equipment and systems to ensure the required load and take into account the evolution of foreseeable requests?','12A02-02','12A02','2','','','E2','12.1.3','10.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2034,'03','QUESTION','Do the installations take into account physical protection?
Protected access, no direct external view on equipment, no multiple physical threats, continuity of power supply, weather conditions, protection against thunderbolts, protection against dust, etc.','12A02-03','12A02','2','','','E2','11.2.1','9.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2035,'04','QUESTION','Is any new or modified functionality linked to a new system or new version of a system, systematically documented before moving into production?','12A02-04','12A02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2036,'05','QUESTION','Is such new functionality (or change in functionality), linked to a new system or new version of a system, formally and systematically reviewed in conjunction with the IT security function?','12A02-05','12A02','2','','','E2','14.2.9','10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2037,'06','QUESTION','Does this review include an analysis of the risks that may  result from the changes? ','12A02-06','12A02','2','2','','E2','14.2.9','10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2038,'07','QUESTION','Have telecommunication  operations staff received formal appropriate training in risk analysis?
This should include service continuity as well as confidentiality and integrity of the data and the transmissions','12A02-07','12A02','1','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2039,'08','QUESTION','May the operation staff obtain an appropriate support specially competent on risk analysis? ','12A02-08','12A02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2040,'09','QUESTION','Are the security measures, determined to counter the new identified risks, formally reviewed before implementation?','12A02-09','12A02','4','2','','E3','14.2.9','10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2041,'10','QUESTION','Are security parameters and configuration rules (deletion of generic accounts, changing of any default passwords, blocking of unauthorized communications ports, setting of access rights and authentication parameters, etc.) listed in detail and regularly updated?','12A02-10','12A02','4','','','E3','14.2.9','10.3.2; 11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2042,'11','QUESTION','Are the security parameters and configuration rules controlled prior to any start of production of a new version? ','12A02-11','12A02','4','','','E3','14.2.9','10.3.2; 11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2043,'12','QUESTION','Has the eventual impact of the systems` changes regarding the continuity plans been considered?','12A02-12','12A02','2','','','E2','14.2.9','10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2044,'13','QUESTION','Are any exemptions from the prerequisite risk analysis and control of security parameters subject to strict procedures, including a signature from senior management?','12A02-13','12A02','4','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2045,'14','QUESTION','Can the start of production of new systems and applications be only carried out by  operations personnel?','12A02-14','12A02','2','2','','E3','12.5.1','6.1.4; 12.4.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2046,'15','QUESTION','Is the start of  production of new versions of systems or applications possible by the use of a defined validation and authorization process? ','12A02-15','12A02','2','2','','E3','12.5.1','6.1.4; 12.4.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2047,'16','QUESTION','Are the start of production control procedures regularly audited?','12A02-16','12A02','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2048,'03','CATEGORY','Control of maintenance operations ','12A03','12A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2049,'01','QUESTION','Is a trace of all maintenance operations kept?','12A03-01','12A03','1','','','E2','11.2.4','9.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2050,'02','QUESTION','Are all maintenance operations required to terminate with a systematic control of physical or recorded configurations and security parameters (as defined at time of start of production)? ','12A03-02','12A03','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2051,'03','QUESTION','Are all maintenance operations required to terminate with a systematic control of the recording parameters for security events and the life span of records?','12A03-03','12A03','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2052,'04','QUESTION','Are all maintenance operations required to terminate with a systematic control of system administration parameters (required profile, authentication type, removal of standard logins etc.)?','12A03-04','12A03','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2053,'05','QUESTION','Is a formal dispensation, signed by a responsible manager, required if the above mentioned procedures are not observed? ','12A03-05','12A03','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2054,'06','QUESTION','Is the effective implementation of these controls regularly audited?','12A03-06','12A03','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2055,'04','CATEGORY','Control of Remote Maintenance ','12A04','12A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2056,'01','QUESTION','In the case of remote maintenance, is the remote maintenance desk`s access subject to a secure authentication procedure?','12A04-01','12A04','2','','2','E2','','11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2057,'02','QUESTION','In the case of remote maintenance, are maintenance staff subject to a secure authentication procedure?','12A04-02','12A04','4','','2','E2','','11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2058,'03','QUESTION','Is there a set of procedures covering the granting and revocation of access rights for remote maintenance operatives and the granting of rights in urgent situations?','12A04-03','12A04','2','','','E3','','11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2059,'04','QUESTION','Does the usage of the remote maintenance line require the prior agreement (for each usage) of telecommunication operations personnel (upon request by the manufacturer or editor specifying the nature, date and time of the intervention)?','12A04-04','12A04','4','3','','E3','','11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2060,'05','QUESTION','Is the usage of the remote maintenance line under strict control?
A strict control supposes that each use of the line, the name of the maintenance operative and the actions carried out is registered, and that there be a subsequent audit of the appropriateness of the actions and their conformity with the rules laid down by maintenance managers.','12A04-05','12A04','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2061,'06','QUESTION','Are control procedures for remote maintenance regularly audited?','12A04-06','12A04','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2062,'05','CATEGORY','Management of Operating Procedures for Telecommunication Operation ','12A05','12A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2063,'01','QUESTION','Do the operating procedures result from the study of the overall cases to be covered by said procedure (normal operating cases and incidents)?','12A05-01','12A05','4','','','E2','12.1.1','10.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2064,'02','QUESTION','Are the operating procedures documented and kept up to date?','12A05-02','12A05','4','','','E2','12.1.1','10.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2065,'03','QUESTION','Are the operating procedures readily available upon request by any accredited individual?','12A05-03','12A05','4','','','E2','12.1.1','10.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2066,'04','QUESTION','Is the telecommunications operation Management required to approve changes to procedures?','12A05-04','12A05','4','','','E2','12.1.1','10.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2067,'05','QUESTION','Are these procedures protected from unauthorized alterations?','12A05-05','12A05','2','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2068,'06','QUESTION','Are the operating procedures audited regularly for authenticity and relevance?','12A05-06','12A05','2','','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2069,'06','CATEGORY','Management of service providers relating to telecommunication','12A06','12A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2070,'01','QUESTION','Is it regularly ensured that the security services allocated to suppliers or providers are efficiently implemented and maintained by them?','12A06-01','12A06','4','','','C1','','10.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2071,'02','QUESTION','Is it ensured that the telecommunications service suppliers or providers  have efficiently prepared the appropriate arrangements to ensure that the services are provided as agreed?','12A06-02','12A06','2','','','E2','','10.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2072,'03','QUESTION','Is the respect of the security provisions by the suppliers or providers regularly reviewed?','12A06-03','12A06','4','','','E1','15.2.1','10.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2073,'04','QUESTION','Is it ensured that the suppliers and providers report and document any security incident concerning information or networks?','12A06-04','12A06','4','','','E2','15.2.1','10.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2074,'05','QUESTION','Is there a regular review of these incidents or malfunctions with the concerned suppliers and providers?','12A06-05','12A06','2','','','E2','15.2.1','10.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2075,'06','QUESTION','Are any changes in the contract relationship (obligations, service levels, etc.) analyzed for resulting potential risks?','12A06-06','12A06','2','','','E3','15.2.2','10.2.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2076,'12','CATEGORY','Control of hardware and software configurations','12B','12','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2077,'01','CATEGORY','Network equipment customizing and compliance control of configurations','12B01','12B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2078,'01','QUESTION','Is an exact inventory of the equipment kept up to date by the concerned responsible persons?
Of key importance with VoIP for the move of terminal equipment and their configuration (including configured emergency call numbers) ','12B01-01','12B01','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2079,'02','QUESTION','Is there a document (or a set of documents ) or an operational procedure which describes all security parameters for the equipment and systems?
Such a document should be derived from the security policy and describe all the filtering rules decided. It should also mention the reference to the system versions so as to check the status of the updates.','12B01-02','12B01','4','2','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2080,'03','QUESTION','Does this document require that all generic or by default accounts be deleted and their list established? ','12B01-03','12B01','4','2','','E2','','11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2081,'04','QUESTION','Are the system versions, fixes and parameters updated regularly in line with latest information?
This should be done in cooperation with expert authorities (specialized audits, subscription to a service center, regular consultation with CERTs, etc.) ','12B01-04','12B01','2','3','','E2','12.6.1','10.7.4; 12.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2082,'05','QUESTION','Does the resulting document or procedure impose a synchronization feature, based on a reliable time reference?','12B01-05','12B01','4','','','E3','12.4.4','10.10.6'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2083,'06','QUESTION','Are these reference documents protected, by secure methods, against untimely or illicit alteration (sealing)?  ','12B01-06','12B01','2','3','','R1','','10.7.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2084,'07','QUESTION','Is the integrity of system configurations checked, regularly (at least weekly) if not at each system start-up, against the configuration theoretically expected?','12B01-07','12B01','4','2','','E3','18.2.3','15.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2085,'08','QUESTION','Are regular audits carried out of the  compliance to the specifications for security parameters?','12B01-08','12B01','2','','','R1','18.2.3','15.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2086,'09','QUESTION','Are regular audits carried out of the exception and escalation procedures in the case of difficulty or installation problems?','12B01-09','12B01','2','','','R1','18.2.3','15.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2087,'10','QUESTION','Are the development and test environments separated from the operational environments?','12B01-10','12B01','1','','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2088,'11','QUESTION','Is it possible to control, each time it is needed, the compliance of the architecture and of the configurations of the equipment? ','12B01-11','12B01','2','2','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2089,'02','CATEGORY','Conformity control of operational software to a reference version ','12B02','12B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2090,'01','QUESTION','Do the telecommunications operations manage a reference version for each equipment or system in operation (source and executable code)? ','12B02-01','12B02','4','2','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2091,'02','QUESTION','Is this reference version protected against all possible illicit or untimely modification (signed media kept by a senior manager, electronic sealing, etc.)?  ','12B02-02','12B02','2','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2092,'03','QUESTION','Is this protection considered to be inviolable (sealing by cryptographic algorithm approved by the Information Security Officer)?  ','12B02-03','12B02','4','','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2093,'04','QUESTION','Is the protective seal controlled automatically (otherwise it may be an authoritative signature) at each new installation?','12B02-04','12B02','4','','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2094,'05','QUESTION','Is a check made of the proof of origin and integrity of received maintenance module or a new version, from the editor or the manufacturer (for operating systems)?  ','12B02-05','12B02','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2095,'06','QUESTION','Are the sealing and sealing control tools protected against any unauthorized usage?','12B02-06','12B02','4','','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2096,'07','QUESTION','Does the inhibition of the automatic control of seals trigger an alarm to a manager?','12B02-07','12B02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2097,'08','QUESTION','Are there regular audits of protection procedures for reference programs? ','12B02-08','12B02','4','','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2098,'12','CATEGORY','Service continuity ','12C','12','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2099,'01','CATEGORY','Organization of operational equipment maintenance','12C01','12C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2100,'01','QUESTION','Is all equipment covered by a maintenance contract?','12C01-01','12C01','2','','','E1','11.2.4','9.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2101,'02','QUESTION','Are there specific maintenance contracts for all hardware which require a high availability and for which the replacement must be made within limited delays? ','12C01-02','12C01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2102,'03','QUESTION','Do the contracts stipulate maximum delays before intervention and compatible with the requirements of availability?','12C01-03','12C01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2103,'04','QUESTION','Do the contracts detail the required time slots and days of intervention (24h/7d for example) compatible with the requirements of availability?','12C01-04','12C01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2104,'05','QUESTION','Do the contracts stipulate the conditions of escalation in case of difficulty?','12C01-05','12C01','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2105,'06','QUESTION','Do the contracts detail specific clauses for when the hardware downtime exceeds the specific times stipulated (penalties, hardware replacement, etc.)?
It is desirable that these clauses be general and apply to all cases no matter what the reasons (technical difficulty, staff strikes, etc.)','12C01-06','12C01','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2106,'07','QUESTION','Do the maintenance contracts anticipate the complete replacement of equipment in the case of important damage which might not be taken into consideration by corrective maintenance?
A special attention should be born on the confidentiality of data stored on the disk of the replaced equipment ','12C01-07','12C01','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2107,'08','QUESTION','Are the maintenance contracts, the choice of subcontractors and associated maintenance procedures subject to regular audit?','12C01-08','12C01','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2108,'02','CATEGORY','Organization of software maintenance (systems and attached services)','12C02','12C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2109,'01','QUESTION','Are there maintenance contracts for all acquired software products (systems software, middleware and applications)?  ','12C02-01','12C02','4','','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2110,'02','QUESTION','Do the suppliers provide a technical software support center which guarantees a quick and competent telephone assistance?','12C02-02','12C02','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2111,'03','QUESTION','Are there specific maintenance contracts for software products (systems, middleware and applications) which require corrective delays that standard maintenance cannot cover?','12C02-03','12C02','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2112,'04','QUESTION','Do these contracts detail specific maximum intervention delays, compatible with the availability requirements?','12C02-04','12C02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2113,'05','QUESTION','Do the contracts detail the required time slots and days of intervention (24h/7d for example) compatible with the requirements of availability?','12C02-05','12C02','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2114,'06','QUESTION','Do the contracts stipulate the conditions of escalation in case of difficulty?','12C02-06','12C02','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2115,'07','QUESTION','Do the contracts specify specific clauses when hardware downtime exceeds specific durations stipulated (penalties, replacement of hardware, etc.)?
It is desirable that these clauses be general and apply to all cases no matter what the reasons (technical difficulty, staff strikes, etc.)','12C02-07','12C02','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2116,'08','QUESTION','Are the maintenance contracts, the choice of subcontractors and associated maintenance procedures subject to regular audit?','12C02-08','12C02','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2117,'03','CATEGORY','Backup of software configurations (system, services and configuration parameters) ','12C03','12C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2118,'01','QUESTION','Has a backup plan been established which covers all programs and defines all objects to save and the frequency of backups?','12C03-01','12C03','4','','','E1','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2119,'02','QUESTION','Does the plan also cover configuration parameters of the telecommunication equipment to save?','12C03-02','12C03','4','3','','E2','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2120,'03','QUESTION','Is the plan implemented by automatic production routines?','12C03-03','12C03','2','3','','E2','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2121,'04','QUESTION','Are there regular tests that the backup copies of configurations enable the effective restoration of the production environment at any time?
These tests should consider all the backups (including documentation and parameters files) of legitimate elements.','12C03-04','12C03','4','2','','E2','12.3.1; 17.1.2; 17.1.3','10.5.1; 14.1.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2122,'05','QUESTION','Are the production routines which ensure backups protected, against illicit or undue modification, by secure mechanisms?
Such mechanisms might be electronic seal or any equivalent modification detection system.','12C03-05','12C03','4','3','','R1','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2123,'06','QUESTION','Are regular tests made of the readability of backups?','12C03-06','12C03','2','3','','R2','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2124,'07','QUESTION','Are all software backup plans and procedures subject to regular audit?','12C03-07','12C03','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2125,'04','CATEGORY','Disaster Recovery Plans','12C04','12C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2126,'01','QUESTION','Have all the scenarios which may impact the telecommunications infrastructure and services been considered and, for each scenario, the consequences in terms of service unavailability for users?
VoIP creates additional requirements for power supply continuity and ability to reconfigure of terminal equipment ','12C04-01','12C04','4','','','E1','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2127,'02','QUESTION','For each scenario, and in agreement with the users, have a list and schedule of service resume been defined?
Loss of information, means to reconstruct them and temporary operational procedures must be considered.','12C04-02','12C04','4','2','','E2','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2128,'03','QUESTION','Has an activity recovery solution been defined and implemented to resolve each scenario identified above, in accordance with user requirements?','12C04-03','12C04','4','','2','E1','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2129,'04','QUESTION','Are the technical, organizational and human resources sufficient to address the organization`s requirements for IT continuity?
This means being able to correct personnel deficiencies','12C04-04','12C04','4','','','E2','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2130,'05','QUESTION','Are the technical, organizational and human resources educated to address the organization`s requirements for continuity?
This implies to train appropriately all concerned staff.','12C04-05','12C04','4','','','E2','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2131,'06','QUESTION','Are all these solutions described in detail in Disaster Recovery Plans including the conditions for triggering the plan, the actions to execute, the priorities, the actors to mobilize and their contact details? ','12C04-06','12C04','4','','','E1','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2132,'07','QUESTION','Are these plans tested at least once a year?','12C04-07','12C04','4','2','','E2','17.1.2; 17.1.3','14.1.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2133,'08','QUESTION','Are above tests able to guarantee that the staff capacity and the recovery systems can cope, under full operational load, the minimum service levels required by users?
The tests required to obtain this guarantee are preferably full scale tests of each variant of scenario, involving all users. The results of the tests have to be registered and analyzed in order to improve the capability of the organization to answer to the situations considered. ','12C04-08','12C04','4','3','','E2','17.1.2; 17.1.3','14.1.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2134,'09','QUESTION','If the recovery solutions include delivery of hardware components (which cannot be triggered during tests), is there a contractual commitment by the manufacturer or any relevant third party (leaser, broker, distributor) to deliver the replacement hardware within fixed and anticipated time limits as stated in the recovery plan?','12C04-09','12C04','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2135,'10','QUESTION','Has the unavailability or failure of the recovery facility been considered and has a replacement solution been defined and validated (second level recovery)?','12C04-10','12C04','2','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2136,'11','QUESTION','Has this (second level  recovery) solution been validated?','12C04-11','12C04','2','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2137,'12','QUESTION','Is the recovery solution usable for an unlimited duration and, if not, has a follow on replacement solution been established?','12C04-12','12C04','2','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2138,'13','QUESTION','Are the existence, the pertinence and the updates of the services Recovery Plans regularly controlled?','12C04-13','12C04','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2139,'14','QUESTION','Is the updating of the above procedures within the recovery plan subject to regular audit?','12C04-14','12C04','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2140,'05','CATEGORY','Management of critical systems (regarding maintenance continuity) ','12C05','12C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2141,'01','QUESTION','Have the consequences of the disappearance of a supplier been analyzed (in the case of failure, a bug or change requirement) and has a list of critical systems been established? 
This is valid for hardware, software or service providers','12C05-01','12C05','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2142,'02','QUESTION','For all critical systems, has a corrective solution been analyzed to cope with the failure or disappearance of a supplier (consignment of maintenance documentation or source code with a trusted third party, hardware replacement by standard market solutions etc.)?','12C05-02','12C05','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2143,'03','QUESTION','Is there a guarantee that the corrective solutions could be made operational within time delays compatible with the continuity of the business and accepted by the users?','12C05-03','12C05','2','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2144,'04','QUESTION','Have variants to the primary solution been considered in case it might encounter unforeseen difficulties?','12C05-04','12C05','2','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2145,'05','QUESTION','Is there a regular review of critical systems and corrective solutions envisaged?','12C05-05','12C05','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2146,'12','CATEGORY','Use of end-user telecommunication equipment ','12D','12','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2147,'01','CATEGORY','Control of the compliance of user configurations ','12D01','12D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2148,'01','QUESTION','Has a list of the telecommunication software authorized on the users` stations been established?
This list should indicate the reference versions authorized and possibly the parameterization options ','12D01-01','12D01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2149,'02','QUESTION','Are these lists protected against untimely or illicit alteration by a robust sealing process?','12D01-02','12D01','2','','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2150,'03','QUESTION','Are the rights provided to users preventing them to modify the specific telecommunication (telephone, audio or video conferencing, etc. )configurations of their equipment?','12D01-03','12D01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2151,'04','QUESTION','Is the conformity of the telecommunication configurations for user workstations regularly controlled relatively to the authorized options? ','12D01-04','12D01','4','2','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2152,'05','QUESTION','Does the inhibition of the control process trigger an alarm to a manager?','12D01-05','12D01','4','3','','C2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2153,'06','QUESTION','Are the processes of control themselves subject to regular audits?','12D01-06','12D01','4','','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2154,'02','CATEGORY','Training and awareness setting for users ','12D02','12D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2155,'01','QUESTION','Are the users made aware of the risks of  tapping resulting from the use of telecommunication equipment and services?','12D02-01','12D02','4','','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2156,'02','QUESTION','Are the users informed of risks resulting from the malevolent usage, locally or remotely, of their communication equipment?
In addition to the use of their colleagues` equipment  without their knowing.','12D02-02','12D02','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2157,'03','QUESTION','Are the deactivation procedures explained to users at the installation or replacement time of their equipment?  ','12D02-03','12D02','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2158,'04','QUESTION','Are the control and security procedures documented? ','12D02-04','12D02','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2159,'05','QUESTION','Are all the users trained about these procedures? ','12D02-05','12D02','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2160,'03','CATEGORY','Utilization of cryptographic equipment','12D03','12D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2161,'01','QUESTION','Are encryption of exchanges mechanisms settable in accordance to the non-disclosure requirements established?','12D03-01','12D03','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2162,'02','QUESTION','Are the encryption capabilities explained to all the staff? ','12D03-02','12D03','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2163,'03','QUESTION','Have the user functions requiring a protection of the telecommunication exchanges been analyzed?','12D03-03','12D03','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2164,'04','QUESTION','Have encryption functions been installed on all the corresponding user equipment? ','12D03-04','12D03','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2165,'12','CATEGORY',' Control of administrative rights','12E','12','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2166,'01','CATEGORY','Management of privileged access rights granted on equipment and systems  (administrative rights) ','12E01','12E','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2167,'01','QUESTION','Have profiles been defined, within telecommunication operations staff, corresponding to each type of activity (system administration, administration of security equipment, system monitoring, management of data storage and backup functions etc.)?','12E01-01','12E01','1','','','E1','6.1.2; 9.2.3; 9.2.5','10.1.3; 11.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2168,'02','QUESTION','For each profile have the necessary rights and privileges been defined? ','12E01-02','12E01','4','2','','E1','6.1.2','10.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2169,'03','QUESTION','Does the process of attributing special rights require the formal authorization of management (or the manager responsible for external service providers) at a sufficiently high level?','12E01-03','12E01','4','2','','E2','6.1.2','10.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2170,'04','QUESTION','Is the process of attributing special rights allocated only in relation to the profile of the holder?','12E01-04','12E01','4','2','','E2','6.1.2','10.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2171,'05','QUESTION','Is the process of granting (modification or revocation) of special rights to an individual strictly controlled?
A strict control requires a formal recognition of the signature (electronic or not) of the requestor, that there be a tight control of access in order to attribute or modify such rights and that any modification of special rights be logged and audited.','12E01-05','12E01','4','2','3','R1','9.2.3; 9.2.5','11.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2172,'06','QUESTION','Is there a systematic process of removal of special rights at the time of departure of telecommunication operations staff?','12E01-06','12E01','2','','','E2','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2173,'07','QUESTION','Is there a systematic process of removal of special rights at the time of role change of telecommunication operations staff?','12E01-07','12E01','2','','','E2','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2174,'08','QUESTION','Is there a regular audit, at least once a year, of all special rights attributed?','12E01-08','12E01','1','2','','C1','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2175,'02','CATEGORY','Authentication and control of the access rights of administrators and operational personnel ','12E02','12E','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2176,'01','QUESTION','Is the authentication protocol used for administrators or holders of special rights considered to be secure?
An authentication protocol is considered secure if it is not susceptible to being broken by a listening device on the network or rendered inoperable by specialists tools (in particular password crack tools ). Such security usually uses cryptographic methods.','12E02-01','12E02','4','','4','E2','6.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2177,'02','QUESTION','Are the rules, for instance in the case of passwords, considered to be very strict?
Strict rules impose the use of tested non-trivial passwords, using a mixture of different types of characters and of a reasonable length (ten characters). It is desirable that these rules have been approved by the Information Security Officer','12E02-02','12E02','2','','','E2','6.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2178,'03','QUESTION','Is there a consistent control of the administrator`s rights, of its context, and of the suitability of this context with the requested access, as per formal rules of access control?','12E02-03','12E02','4','','','E2','6.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2179,'04','QUESTION','Are authentication parameters under strict control?
A strict control requires that the list of people able to change authentication rules, the credentials themselves and the surveillance rules of connection attempts be strictly limited, that there be a reinforced access control in order to be able to modify these rights and that any modification of these rights be logged and audited and that there be a general audit at least once a year of all authentication parameters.','12E02-04','12E02','4','2','','R1','6.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2180,'05','QUESTION','Are the processes that guarantee authentication under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (seal) and that there is an audit at least once a year of the authentication procedures and processes.','12E02-05','12E02','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2181,'06','QUESTION','Is there a regular audit of the security parameters attached to protecting profiles and rights?','12E02-06','12E02','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2182,'03','CATEGORY','Surveillance of system administrators` actions over the equipment and systems','12E03','12E','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2183,'01','QUESTION','Has a detailed analysis been carried out of the events and operations carried out with administrative rights which may potentially have an impact on system security (configuration of security systems, access to sensitive information, usage of sensitive tools, download or modification of administrative tools etc.)?','12E03-01','12E03','2','','','E2','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2184,'02','QUESTION','Are these events recorded as well as all parameters which may be useful for their subsequent analysis? ','12E03-02','12E03','4','','','E2','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2185,'03','QUESTION','Is there a system able to detect any modification or deletion of a past record and to immediately trigger an alarm to a manager? ','12E03-03','12E03','4','2','','E3','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2186,'04','QUESTION','Is there a summary of these records enabling management to detect abnormal behavior?','12E03-04','12E03','4','','3','E3','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2187,'05','QUESTION','Is there a system enabling the detection of any modification of recording parameters and to immediately trigger an alarm to a manager? ','12E03-05','12E03','4','2','','E3','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2188,'06','QUESTION','Does any inhibition of the recording and processing of the logged events system trigger an alarm to a manager? ','12E03-06','12E03','4','','','E3','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2189,'07','QUESTION','Are all records or summary analyses protected against any falsification or destruction?','12E03-07','12E03','2','','','E2','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2190,'08','QUESTION','Are all records or summary analyses kept for a long period?','12E03-08','12E03','2','','','E2','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(2191,'09','QUESTION','Are the procedures, which record and process privileged operations, regularly audited? ','12E03-09','12E03','2','','','C1','12.4.3','10.10.4'); 
