INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(545,'04','QUESTIONNAIRE','MEHARI_ExtendedNetwork','04','','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(546,'04','CATEGORY','Security of the Wide-area Network architecture and service continuity','04A','04','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(547,'01','CATEGORY','Functional security of the Wide-area Network architecture','04A01','04A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(548,'01','QUESTION','Have the requirements of service continuity of the Wide-area Network been analyzed and, if necessary, has a redundant architecture been determined for network connection points, equipment and network meshing?','04A01-01','04A01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(549,'02','QUESTION','Has a systematic search for single points of failure been carried out and has it been ensured that subsidiary equipment (power supply and air conditioning etc.) does not introduce or eliminate the redundancy expected in the equipment or network architecture?','04A01-02','04A01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(550,'03','QUESTION','Has a verification of the average and peak load been carried out for each segment of the Wide-area Network and has the compatibility of the network and associated equipment at this load level been verified and is this verification regularly repeated?','04A01-03','04A01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(551,'04','QUESTION','Has this analysis been complemented by a study of network capacity to ensure reliability of communications in all cases of failure of a single link or piece of equipment?','04A01-04','04A01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(552,'05','QUESTION','Is there a dynamic measurement of network load and are load balancing tools available?','04A01-05','04A01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(553,'06','QUESTION','Do network monitoring and configuration tools allow real time corrective action compatible with the needs of the users?','04A01-06','04A01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(554,'07','QUESTION','Are overload detection and load balancing tools accessible only by administrators and are they protected by strengthened access control?','04A01-07','04A01','2','2','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(555,'08','QUESTION','Is any failure or shutdown of network overload detection and equilibrating equipment signaled immediately to the monitoring center and to network administrators?','04A01-08','04A01','2','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(556,'09','QUESTION','Are regular performance tests of load detection equipment and reconfiguration mechanisms carried out?','04A01-09','04A01','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(557,'10','QUESTION','Are regular audits carried out of equipment parameters and procedures associated with the load detection and reconfiguration systems?','04A01-10','04A01','1','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(558,'11','QUESTION','Are regular audits carried out of the procedures associated to the load detection and  reconfiguration systems?','04A01-11','04A01','1','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(559,'02','CATEGORY','Management of Wide-area Network equipment maintenance','04A02','04A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(560,'01','QUESTION','Is all equipment covered by a maintenance contract?','04A02-01','04A02','2','','','E1','11.2.4','9.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(561,'02','QUESTION','Has all critical production equipment been identified, has their performance capability been controlled and have the acceptable and maximum downtime limits been documented?','04A02-02','04A02','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(562,'03','QUESTION','Have specifically adapted clauses related to these requirements been set down within maintenance contracts?','04A02-03','04A02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(563,'04','QUESTION','Are the penalties of non-compliance with these clauses sufficiently persuasive for the contract holder?','04A02-04','04A02','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(564,'05','QUESTION','Have escalation procedures been detailed in the case of non-compliance or difficulties in maintenance and do they anticipate the intervention of specialists within a short delay commensurate with the criticality of the equipment?','04A02-05','04A02','2','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(565,'06','QUESTION','Has the number and proximity of specialists been detailed and do they guarantee a sufficiently good level of maintenance within an acceptable period of time?','04A02-06','04A02','4','','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(566,'07','QUESTION','Do the maintenance contracts anticipate a complete replacement of equipment in the case of significant damage which would not normally be taken into account by curative maintenance?','04A02-07','04A02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(567,'08','QUESTION','Are maintenance contracts and procedures regularly audited?','04A02-08','04A02','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(568,'03','CATEGORY','Procedures and Business Contingency Planning following incidents on the Wide-area Network','04A03','04A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(569,'01','QUESTION','Has a list been established of incidents which could affect the proper functioning of the Wide-area Network and analyzed the seriousness level, for each of them?','04A03-01','04A03','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(570,'02','QUESTION','Has it been established, for each critical incident, the solution to implement and the action to execute by operational personnel? ','04A03-02','04A03','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(571,'03','QUESTION','Have sufficient means of intervention (reconfiguration) on the Wide-area Network been put in place which cover satisfactorily all of the scenarios identified and do they allow for the actions decided to be implemented within the specified delays?','04A03-03','04A03','2','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(572,'04','QUESTION','For each possible critical incident on the Wide-area Network has an expected resolution time and escalation procedure been determined in the case of failure or delay of the specified corrective actions?','04A03-04','04A03','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(573,'05','QUESTION','Are the diagnostic, management and reconfiguration tools of the Wide-area Network protected against all possible untimely or malicious action?','04A03-05','04A03','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(574,'06','QUESTION','Do incident recovery plans and procedures cover the eventual loss of data (especially e-mail messages)?','04A03-06','04A03','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(575,'07','QUESTION','Are diagnostic and reconfiguration facilities regularly audited in order to assure a satisfactory minimum functioning of the Wide-area Network in the case of an incident?','04A03-07','04A03','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(576,'04','CATEGORY','Backup plan of Wide-area Network configurations','04A04','04A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(577,'01','QUESTION','Has a backup plan been established encompassing all network configurations, defining all objects to save and the frequency of backups?','04A04-01','04A04','4','','','E1','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(578,'02','QUESTION','Has this plan been translated into automatic operational routines?','04A04-02','04A04','2','2','','E2','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(579,'03','QUESTION','Has the backup of programs, (source and executables), documentation and parameters been regularly tested in order to be able to reconstitute the production environment at any time?','04A04-03','04A04','4','2','','E1','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(580,'04','QUESTION','Are operational automatic routines protected by a high level of protection against illicit or unintentional modification? 
Such a mechanism may be a digital seal or any equivalent protection system.','04A04-04','04A04','4','3','','R1','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(581,'05','QUESTION','Are all configuration backups and files which enable the restoration of the Wide-area Network production environment also saved at a location off premises (recourse backup)?','04A04-05','04A04','4','2','','E3','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(582,'06','QUESTION','Are recourse backup copies stored in a secure location and protected against accidental risk or theft?
Such a location must be protected by strict access control as well as protected against fire or water damage risk.','04A04-06','04A04','4','','','E3','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(583,'07','QUESTION','Are regular tests carried out to read backups and recourse backups?','04A04-07','04A04','2','3','','C1','12.3.1','10.5.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(584,'08','QUESTION','Are all procedures and plans for backup of configuration files regularly audited?','04A04-08','04A04','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(585,'05','CATEGORY','Business Contingency Planning (BCP) of the Wide-area Network','04A05','04A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(586,'01','QUESTION','Is there an operational recovery solution to make up for the unavailability of any critical equipment or link on the Wide-area Network?','04A05-01','04A05','4','','2','E1','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(587,'02','QUESTION','Is this recovery solution satisfactorily operational?','04A05-02','04A05','4','','2','E2','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(588,'03','QUESTION','Are these alternative solutions described in detail in one (or several) Disaster Recovery Plan formal and complete?
A complete recovery plan must include the conditions for triggering, the actions to execute, the priorities, the actors to mobilize and their contact details as well as the conditions for considering the return to the normal state. ','04A05-03','04A05','4','','','E1','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(589,'04','QUESTION','Are these plans tested in operational conditions at least once a year?','04A05-04','04A05','4','2','','C1','17.1.2','14.1.5; 17.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(590,'05','QUESTION','Is there a formal guarantee that the capacity and compatibility of these recovery solutions will support a sufficient operational load which has been approved by all connected entities?','04A05-05','04A05','4','2','','E2','17.1.2','14.1.5; 17.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(591,'06','QUESTION','If the recovery solutions include delivery of hardware components which cannot be triggered during tests, is there a contractual engagement within the recovery plan for the delivery of the replacement hardware within fixed and anticipated time limits guaranteed by the manufacturer or other third party (leaser, broker, other)?','04A05-06','04A05','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(592,'07','QUESTION','If the recovery facility (hot site, equipment etc.) is subscribed through a service provider, is the number of other subscribers known and limited?','04A05-07','04A05','2','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(593,'08','QUESTION','Has the possible unavailability or failure of the recovery facility been considered and has a second level backup been organized?','04A05-08','04A05','2','','3','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(594,'09','QUESTION','Is the backup solution usable for an unlimited duration and, if not, has a follow on backup solution been established?','04A05-09','04A05','2','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(595,'10','QUESTION','Are the existence, the pertinence and the updates of the Disaster Recovery Plans regularly audited?','04A05-10','04A05','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(596,'06','CATEGORY','Management of critical suppliers as regards a permanent maintenance service','04A06','04A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(597,'01','QUESTION','Have the consequences of the disappearance of a supplier of equipment, network service or software been analyzed (in the case of failure, a bug or change requirement) and has a list of critical points been established? ','04A06-01','04A06','2','','','E2','15.1.3; 17.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(598,'02','QUESTION','For each critical point is there a corrective solution to cope with the failure or disappearance of a supplier (consignment of maintenance documentation with a trusted third party, replacement of equipment or of software by available market solutions etc.)?','04A06-02','04A06','2','','','E2','15.1.3; 17.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(599,'03','QUESTION','Is it certain that this corrective solution could be made operational to enable company activity to restart within a time delay sufficiently short to be acceptable to the users ?','04A06-03','04A06','2','2','','E3','17.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(600,'04','QUESTION','Have variants to the primary solution been considered in case the latter might encounter unforeseen difficulties?','04A06-04','04A06','2','3','','E3','17.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(601,'05','QUESTION','Is there a regular review of critical points and corrective solutions envisaged?','04A06-05','04A06','2','3','','C1','17.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(602,'04','CATEGORY','Control of connections on the Wide-area Network ','04B','04','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(603,'01','CATEGORY','Security profiles for entities connected to the Wide-area Network','04B01','04B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(604,'01','QUESTION','Has a set of rules been defined such that an entity can be connected to the Wide-area Network (which is considered to be a domain of confidence)? ','04B01-01','04B01','4','','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(605,'02','QUESTION','Do these rules cover the necessary organization for each entity connected to the network?','04B01-02','04B01','2','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(606,'03','QUESTION','Within each entity connected, are  managers designed and known responsible of security in various domains (such as physical security, operating systems security, etc.)? ','04B01-03','04B01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(607,'04','QUESTION','Do the rules establishing the connection criteria to the Wide-area Network define the physical security measures required to protect the network equipment and cabling?','04B01-04','04B01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(608,'05','QUESTION','Do these rules establishing the connection criteria to the Wide-area Network define the logical security measures required to protect the network equipment and cabling?','04B01-05','04B01','2','','','E2','','11.4.6'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(609,'06','QUESTION','Do these rules detail the filtering rules required for the control of incoming as well as outgoing accesses?','04B01-06','04B01','4','2','','E2','','11.4.6'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(610,'07','QUESTION','Do these rules detail controls to effect on the network equipment configurations?','04B01-07','04B01','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(611,'08','QUESTION','Do these rules detail controls to effect on the configurations of users stations?','04B01-08','04B01','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(612,'09','QUESTION','Do these rules define the required management methods to cover anomalies and incidents?','04B01-09','04B01','2','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(613,'10','QUESTION','Do these rules impose to send a report to a central authority for any anomaly and incident challenging the security of the Wide-area Network?','04B01-10','04B01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(614,'11','QUESTION','Is there a management procedure covering the authorization requests for the binding of any entity to the Wide-area Network and a structure empowered to analyze these requests and provide the corresponding authorization?','04B01-11','04B01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(615,'12','QUESTION','Is there a structure empowered to audit the application of the rules and to remove specific rights which are no longer needed or when the conditions are no longer met?','04B01-12','04B01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(616,'13','QUESTION','Is there a regular audit of the required conditions and application of the rules in each entity authorized to be part of the Wide-area Network?','04B01-13','04B01','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(617,'14','QUESTION','Are reviews of the authorized connections (standard and non-standard) and of their relevance regularly conducted?','04B01-14','04B01','4','3','','C1','','11.4.7'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(618,'02','CATEGORY','Authentication of the entity for an incoming access from the Wide-area Network','04B02','04B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(619,'01','QUESTION','Is there, for any access arriving from the Wide-area Network to the local area network, a mechanism controlling the authentication and access control rights of the accessing entity prior to any action?','04B02-01','04B02','4','1','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(620,'02','QUESTION','Does the authentication mechanism provide a recognized strong level of security?
Notably the usage of a simple password will always be a weakness. The only methods recognized as strong, that is to say observable without divulging information, are those based on cryptographic algorithms.','04B02-02','04B02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(621,'03','QUESTION','Does the security equipment that retains and uses reference data (secret elements) to support access authentication use mechanisms which guarantee inviolability and authenticity?
In the case of authentication using cryptographic procedures, the mechanisms used for the creation, modification and storage of reference elements (public keys in particular) must guarantee a level of security comparable to the authentication protocol itself.','04B02-03','04B02','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(622,'04','QUESTION','Does the transmission between systems and security equipments of reference data (secret elements, secret or public keys, etc.) use mechanisms which guarantee inviolability and authenticity?
In the case of authentication using cryptographic procedures, the mechanisms used for the transmission of reference elements (public keys in particular) must guarantee a level of security comparable to the authentication protocol itself.','04B02-04','04B02','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(623,'05','QUESTION','Does the management procedure of revoked keys systematically test that the keys have not been revoked?','04B02-05','04B02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(624,'06','QUESTION','Does the management procedure of revoked keys guarantee that the control systems take in consideration in real time any revocation?','04B02-06','04B02','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(625,'07','QUESTION','Are the processes that guarantee authentication under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (seal) and that there is an audit at least once a year of the authentication procedures and processes.','04B02-07','04B02','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(626,'03','CATEGORY','Authentication of the entity accessed for an outgoing access across the Wide-area Network','04B03','04B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(627,'01','QUESTION','Is there a mechanism for the authentication of the called entity before any outgoing access from the internal network across the Wide-area Network?','04B03-01','04B03','4','1','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(628,'02','QUESTION','Is the authentication mechanism recognized as strong?
The only methods recognized as strong, that is to say observable without divulging information, are those based on cryptographic algorithms.','04B03-02','04B03','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(629,'03','QUESTION','Does the security equipment that retains and uses reference data (secret elements) to support authentication use mechanisms which guarantee inviolability and authenticity?
In the case of authentication using cryptographic procedures, the mechanisms of modification, storage and transmission of reference elements (public keys in particular) must use a level of security comparable to the authentication protocol itself.','04B03-03','04B03','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(630,'04','QUESTION','Does the transmission between equipments of reference data (secret elements) to support authentication use mechanisms which guarantee inviolability and authenticity?
In the case of authentication using cryptographic procedures, the mechanisms of transmission of reference elements (secret elements, public keys, etc.) must guarantee a level of security comparable to the authentication protocol itself.','04B03-04','04B03','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(631,'05','QUESTION','Does the revoked keys management procedure  guarantee that the control systems systematically test that the keys used have not been revoked?','04B03-05','04B03','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(632,'06','QUESTION','Does the revoked keys management procedure  guarantee that the control systems take into consideration in real time any revocation of keys?','04B03-06','04B03','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(633,'07','QUESTION','Are the processes that guarantee authentication under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (seal) and that an audit is performed at least once a year of authentication procedures and processes.','04B03-07','04B03','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(634,'04','CATEGORY','Security during data exchanges and communication ','04C','04','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(635,'01','CATEGORY','Encryption of exchanges on the Wide-area Network
Encryption can be effected at layer 2 (encrypting modem ), 3 (IPSEC VPN) or at level 4-5 (SSL) or directly effected by the application (level 6-7, for example encryption before or during transmission), case really treated by domain 09 
It could be systematically on the pipeline (physical or logical) or limited only to certain data flows (as a function of address or type, etc.) it can also be performed on intermediate systems (VPN boxes) or end systems (stations, server) or both.','04C01','04C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(636,'01','QUESTION','Have the permanent links and data exchanges which must be protected by encryption solutions been defined and such solutions been implemented on the Wide-area Network?','04C01-01','04C01','4','','','E2','10.1.1','12.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(637,'02','QUESTION','Does the encryption solution offer valid and solid guarantees and has it been approved by the Information Security Officer?  
The sufficient length of the key is one of among many parameters to take into consideration (as a function of the algorithm) . The recommendation of an official organization can be a confidence factor.','04C01-02','04C01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(638,'03','QUESTION','Do the procedure and mechanisms of storage, distribution and exchange of keys and more generally the management of the keys offer solid guarantees which merit confidence and are they approved by the Information Security Officer?','04C01-03','04C01','4','3','','E3','10.1.2','12.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(639,'04','QUESTION','Are the encryption mechanisms embodied in electronic components which are strictly protected at a physical level against intrusion or change? 
Encryption mechanisms should be contained within protected enclosures to which it should be impossible to gain a','04C01-04','04C01','4','3','3','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(640,'05','QUESTION','Is shutdown or by-pass of the encryption solution immediately detected and signaled to a team available 24 hrs a day capable of triggering an immediate reaction?','04C01-05','04C01','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(641,'06','QUESTION','In the case of inhibition or bypass of the encryption solution or the activation of an unprotected fail-over link of the network, is there a procedure to immediately alert all users?
For example by a warning requiring the user to acknowledge its receipt.','04C01-06','04C01','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(642,'07','QUESTION','Is there a regular audit, at least once a year, of all data exchange, encryption systems and associated procedures?','04C01-07','04C01','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(643,'02','CATEGORY','Integrity control of exchanges on the Wide-area Network','04C02','04C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(644,'01','QUESTION','Have all data exchanges and permanent links which must be protected by sealing solutions been defined and implemented on the Wide-area Network?','04C02-01','04C02','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(645,'02','QUESTION','Does the sealing solution offer valid and solid guarantees and has it been approved by the Information Security Officer?  
The sufficient length of the key is one of among many parameters to take into consideration (as a function of the algorithm) . The recommendation of an official organization can be a confidence factor.','04C02-02','04C02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(646,'03','QUESTION','Do the procedure and mechanisms for storage, distribution and exchange of keys and more generally the management of keys offer a sufficient level of confidence and have they been approved by the Information Security Officer?','04C02-03','04C02','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(647,'04','QUESTION','Are the sealing mechanisms embodied in electronic components which are in turn strictly protected at a physical level against intrusion or change? 
Sealing mechanisms should be contained within protected enclosures to which it should be impossible to gain access. The algorithm is contained within the microprocessor or a microprocessor card which is protected physically and logically.','04C02-04','04C02','4','3','3','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(648,'05','QUESTION','Is shutdown or by-pass of the sealing solution immediately detected and signaled to a team available 24 hrs a day capable of triggering an immediate reaction?','04C02-05','04C02','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(649,'06','QUESTION','In the case of inhibition or bypass of the sealing solution or the activation of an unprotected fail-over link, is there a procedure to immediately alert all users?
For example by a warning requiring the user to actively validate its receipt.','04C02-06','04C02','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(650,'07','QUESTION','Is there a regular audit, at least once a year, of all systems of sealing of the data exchanged and associated procedures?','04C02-07','04C02','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(651,'04','CATEGORY','Control, Detection and Handling of incidents on the Wide-area Network ','04D','04','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(652,'01','CATEGORY','Real-time monitoring of the Wide-area Network','04D01','04D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(653,'01','QUESTION','Have events or successions of events which might reveal abnormal behavior or illicit action on the Wide-area Network been analyzed and, as a consequence, have specific monitoring points and indicators been established?','04D01-01','04D01','4','','','E2','12.4.1; 16.1.4','10.10.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(654,'02','QUESTION','Is the system equipped with an automatic real time monitoring system in the case of an accumulation of abnormal events (for example unsuccessful connection attempts on non-open ports)?','04D01-02','04D01','4','','','E3','12.4.1; 16.1.4','10.10.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(655,'03','QUESTION','Is use made of a system capable of detecting intrusion and anomalies on the Wide-area Network?','04D01-03','04D01','4','','','E2','12.4.1; 16.1.4','10.10.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(656,'04','QUESTION','Are there one or more applications capable of analyzing the individual anomaly diagnostic data on the Wide-area Network and of triggering an alert to operational personnel?','04D01-04','04D01','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(657,'05','QUESTION','Is there within operational personnel a permanent dedicated team or group capable of reacting in the case of a monitoring alert on the Wide-area Network?','04D01-05','04D01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(658,'06','QUESTION','For each case of alert has the expected response from the intervention team been defined and is the availability of the intervention team sufficient to face this expectation?','04D01-06','04D01','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(659,'07','QUESTION','Are the parameters defining alarms strictly protected (restricted access rights and strict authentication ) against illicit modification?','04D01-07','04D01','4','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(660,'08','QUESTION','Does the inhibition of an alert system on the Wide-area Network, trigger an alarm with the surveillance team?','04D01-08','04D01','4','3','','R1','12.4.1','10.10.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(661,'09','QUESTION','Are the elements which enable the detection of an anomaly or incident archived (on disk, cassette or optical disk etc.)?','04D01-09','04D01','2','','','E2','12.4.2','10.10.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(662,'10','QUESTION','Are the procedures for monitoring the Wide-area Network, for the detection of the anomalies and the reactivity of the surveillance team subject to regular audit?','04D01-10','04D01','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(663,'02','CATEGORY','Offline analysis of traces, log files and event journals on the Wide-area Network ','04D02','04D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(664,'01','QUESTION','Has detailed analysis been carried out of the events or succession of events on the Wide-area Network which may have had an impact on security (refused connections, re-routings, reconfigurations, changes in performance, access to sensitive data or tools etc.)?','04D02-01','04D02','2','','','E1','12.4.1','10.10.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(665,'02','QUESTION','Are these events recorded as well as the parameters used for their subsequent analysis?','04D02-02','04D02','4','','','E1','12.4.1','10.10.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(666,'03','QUESTION','Is there an application capable of analyzing these records as well as performance measures, of establishing statistics, a dashboard and anomaly diagnostics for examination by a competent team of specialists?','04D02-03','04D02','4','2','3','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(667,'04','QUESTION','Is the structure empowered to analyze these summaries (or incidents logs and security related events) required to do so within a fixed and determined period and does it have sufficient availability?','04D02-04','04D02','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(668,'05','QUESTION','Has the expected response from the surveillance team been defined for each case of alert and are its availability and staffing level sufficient to meet these expectations?','04D02-05','04D02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(669,'06','QUESTION','Are the parameters defining the elements to record and the analysis to effect strictly protected against unauthorized change (limited rights and strong authentication)?','04D02-06','04D02','4','','','R1','12.4.2','10.10.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(670,'07','QUESTION','Is any inhibition of the recording and processing system immediately signaled to the surveillance team?','04D02-07','04D02','4','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(671,'08','QUESTION','Are the records and summary analysis protected against any destruction or modification?','04D02-08','04D02','2','','','E2','12.4.2','10.10.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(672,'09','QUESTION','Are the records and summary analysis kept for a long period?','04D02-09','04D02','2','','','E2','12.4.2','10.10.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(673,'10','QUESTION','Are the procedures for recording, processing and analyzing of the records and summaries as well as the availability of the analysis and corrective team subject to regular audit?','04D02-10','04D02','2','','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(674,'03','CATEGORY','Management of incidents on the Wide-area Network','04D03','04D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(675,'01','QUESTION','Is there a hot-line charged with taking and recording calls related to the Wide-area Network and to escalate all incidents?','04D03-01','04D03','2','','','E1','12.4.1; 16.1.5','10.10.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(676,'02','QUESTION','Is this hot-line team available 24 hours a day?','04D03-02','04D03','2','','','E2','12.4.1; 16.1.5','10.10.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(677,'03','QUESTION','Is there a system to support incident management?','04D03-03','04D03','2','2','','E2','12.4.1; 16.1.5','10.10.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(678,'04','QUESTION','Does this system centralize incidents detected both by operational personnel and by users?','04D03-04','04D03','2','','','E2','12.4.1; 16.1.5','10.10.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(679,'05','QUESTION','Does the system cater for a systematic follow-up of necessary actions?','04D03-05','04D03','4','','','E3','12.4.1; 16.1.5','10.10.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(680,'06','QUESTION','Does this system incorporate a categorization of incidents including statistics and dashboards generation destined for use by the Information Security Officer?','04D03-06','04D03','4','','','E3','16.1.1; 16.1.5',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(681,'07','QUESTION','Is the incident management system strictly controlled with regard to unauthorized or illicit modification?
A strict control requires a reinforced protection in order to modify records and an audit trail or protection by electronic seal of all modifications of records.','04D03-07','04D03','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(682,'08','QUESTION','Is each major incident on the network subject to a specific follow-up (nature and description, priority, technical solution, progress analysis, expected resolution lead time etc.)?','04D03-08','04D03','4','','','E2','16.1.1','13.2.1'); 
