INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(901,'06','QUESTIONNAIRE','MEHARI_NetworkOperations','06','','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(902,'06','CATEGORY','Security of operations procedures ','06A','06','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(903,'01','CATEGORY','Security in the relationship with operational personnel (employees, suppliers or service providers)','06A01','06A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(904,'01','QUESTION','Is there a security policy specifically aimed at operational network personnel covering all the aspects of information security (confidentiality of information, service and information availability, integrity of information and configurations, trace ability, etc. )?  ','06A01-01','06A01','4','1','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(905,'02','QUESTION','Is operational network personnel required to sign contract clauses of adherence to that security policy (no matter their status: permanent or temporary staff, students, etc.)?','06A01-02','06A01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(906,'03','QUESTION','Do these clauses make clear that the obligation to respect security applies to all information no matter what the medium is (paper, magnetic, optical, etc.)?','06A01-03','06A01','2','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(907,'04','QUESTION','Do these clauses make clear, if necessary and legally possible, that the obligation to respect the security policy applies without limitation in time? 
This applies, in particular, to the clauses concerning confidentiality, they may (and often must) continue after the end of the contract linking (directly or indirectly) the employee or  service provider or partner to the company','06A01-04','06A01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(908,'05','QUESTION','Do these clauses make clear that the personnel has an obligation not to tolerate any action contrary to security from other people?','06A01-05','06A01','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(909,'06','QUESTION','Does the signature of these clauses represent a formal commitment?
In order to achieve a formal commitment, the personnel should explicitly state that his/her signature implies having understood and accepted the security policy','06A01-06','06A01','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(910,'07','QUESTION','Are these same clauses obligatory for contractors working on network operations?
Practically, the contractors should ensure that their personnel sign individually and explicitly under the same conditions than internal staff.','06A01-07','06A01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(911,'08','QUESTION','Is there a mandatory and well adapted training course aimed at network operations personnel?','06A01-08','06A01','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(912,'09','QUESTION','Are the confidentiality agreements, signed by personnel, securely kept (at least in a locked cupboard )?  ','06A01-09','06A01','2','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(913,'10','QUESTION','Are the confidentiality agreements, signed by external contractors, securely kept (at least in a locked cupboard )?  ','06A01-10','06A01','2','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(914,'11','QUESTION','Is there a regular audit, at least once a year, of the effective application of the signature procedure by  operational personnel (directly employed by the company or indirectly through a service company)?','06A01-11','06A01','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(915,'02','CATEGORY','Control of the implementation or upgrade of software or hardware ','06A02','06A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(916,'01','QUESTION','Is there a control procedure for change decisions, equipment and system evolutions (registration, planning, formal approbation, communication to all concerned individuals, etc.)?','06A02-01','06A02','2','2','','E1','12.1.2','10.1.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(917,'02','QUESTION','Are the change decisions based on an analysis of the capacity of the new equipment and systems in ensuring the required load taking into account the evolution of foreseeable requests?','06A02-02','06A02','2','','','E2','12.1.3','10.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(918,'03','QUESTION','Do the installations take into account physical protection (protected access, no direct external view to equipments, absence of physical threats, climate conditions, protection against thunderbolts, protection against dust, etc.)?','06A02-03','06A02','2','','','E2','11.2.1','9.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(919,'04','QUESTION','Is there a definite review, involving Information Security Office personnel, of the potential risks related to functional changes associated to each new or revised network software or equipment?','06A02-04','06A02','2','','','E2','12.5.1; 14.2.9','12.4.1; 10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(920,'05','QUESTION','Does this review contain an analysis of the risks that may arise from these functional changes?','06A02-05','06A02','2','2','','E2','12.5.1; 14.2.9','12.4.1; 10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(921,'06','QUESTION','Has operational staff received specific formal training in risk analysis?','06A02-06','06A02','1','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(922,'07','QUESTION','Does operational staff obtain appropriate advice when needed?','06A02-07','06A02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(923,'08','QUESTION','Are security measures, to be implemented to counter any new risks identified, subject to formal review and control before start of production?','06A02-08','06A02','4','','','E2','14.2.9','10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(924,'09','QUESTION','Are security parameters and configuration rules (removal of all generic accounts, changing of generic passwords, closure of all ports not specifically requested and authorized, access control and authentication parameters, control of routing tables etc.) detailed and kept up to date and are they reviewed before any start of production of a new version?','06A02-09','06A02','4','','','E2','14.2.9','11.4.4; 10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(925,'10','QUESTION','Are the security parameters and configuration rules controlled before any new version is installed and operated? ','06A02-10','06A02','4','','','E2','14.2.9','11.4.4; 10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(926,'11','QUESTION','Is it considered the possible impact over the continuity plans due the system changes?','06A02-11','06A02','2','','','E2','14.2.9','10.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(927,'12','QUESTION','Are any exemptions from the prior risk analysis and control of security parameters subject to strict procedures requiring the signature of a senior manager?','06A02-12','06A02','4','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(928,'13','QUESTION','Is the start of production of new equipment or software only possible by operational staff?','06A02-13','06A02','4','2','','E2','12.5.1','12.4.1; 6.1.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(929,'14','QUESTION','Is the start of production of new equipment or software only possible following a defined validation and authorization process?','06A02-14','06A02','2','3','','E3','12.5.1','12.4.1; 6.1.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(930,'15','QUESTION','Are all the control procedures related to start of production subject to regular audit?','06A02-15','06A02','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(931,'03','CATEGORY','Control of maintenance operations ','06A03','06A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(932,'01','QUESTION','Is it kept a trace of all maintenance operations?','06A03-01','06A03','1','','','E2','11.2.4','9.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(933,'02','QUESTION','Are all maintenance operations required to terminate with a systematic verification of all security parameters (as defined at the start of production)?  ','06A03-02','06A03','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(934,'03','QUESTION','Are all maintenance operations required to terminate with a systematic verification of security log files parameters (events to be recorded, context of events to be recorded, duration of retention, etc.)?','06A03-03','06A03','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(935,'04','QUESTION','Are all maintenance operations required to terminate with a systematic verification of administration control parameters (necessary profile, authentication type, removal of standard logins, etc.)?  ','06A03-04','06A03','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(936,'05','QUESTION','Is a formal exemption, signed by a responsible manager, required if the above mentioned procedures are not observed? ','06A03-05','06A03','4','','','E3','','14.2.9'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(937,'06','QUESTION','Is the totality of start of production (after maintenance) control procedures regularly audited?','06A03-06','06A03','2','3','','C1','','14.2.9'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(938,'04','CATEGORY','Control of Remote Maintenance ','06A04','06A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(939,'01','QUESTION','In the case of remote maintenance, is there a secure authentication procedure of the remote maintenance center?','06A04-01','06A04','2','','','E2','','11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(940,'02','QUESTION','In the case of remote maintenance is there a secure authentication procedure for maintenance personnel? ','06A04-02','06A04','4','','2','E2','','11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(941,'03','QUESTION','Is there a set of procedures covering the attribution of access rights for a new maintenance operative, the revocation of rights and the attribution of rights in emergency situations? ','06A04-03','06A04','2','','','E3','','11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(942,'04','QUESTION','Have the procedures and protocols for the exchange and storage of secret data etc., been approved by the Information Security Officer or a specialized organization? ','06A04-04','06A04','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(943,'05','QUESTION','Does the usage of the remote maintenance line require the prior agreement (for each usage) of operational personnel (following the provider`s request specifying the nature, date and time of the intervention )?  ','06A04-05','06A04','4','','','E2','','11.4.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(944,'06','QUESTION','Is the equipment allocated for remote maintenance protected against inhibition or modification of access conditions, resulting in the triggering of an alarm? ','06A04-06','06A04','2','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(945,'07','QUESTION','Are all the control procedures for remote maintenance regularly audited?','06A04-07','06A04','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(946,'05','CATEGORY','Management of Operating Procedures for Network Operation','06A05','06A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(947,'01','QUESTION','Do the network operating  procedure result from the study of the overall cases to be covered by said procedure (normal operating cases and incidents)?','06A05-01','06A05','4','','','E2','12.1.1','10.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(948,'02','QUESTION','Are the operating procedures documented and kept up to date?','06A05-02','06A05','4','','','E2','12.1.1','10.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(949,'03','QUESTION','Are these operating procedures readily available upon request by any accredited individual?','06A05-03','06A05','4','','','E2','12.1.1; 15.2.1','10.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(950,'04','QUESTION','Does the Management approve changes to procedures ?','06A05-04','06A05','2','','','E2','12.1.1; 15.2.1','10.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(951,'05','QUESTION','Are these procedures protected from unauthorized alterations?','06A05-05','06A05','2','','','R1','15.2.1',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(952,'06','QUESTION','Are the operating procedures audited regularly for authenticity and relevance?','06A05-06','06A05','2','','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(953,'06','CATEGORY','Management of service providers relating to networks','06A06','06A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(954,'01','QUESTION','Is it ensured regularly that the network security services allocated to suppliers or service providers are efficiently implemented and maintained by them?','06A06-01','06A06','4','','','C1','12.6.1','10.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(955,'02','QUESTION','Is it ensured that the above suppliers have efficiently prepared the appropriate arrangements to ensure that the services are provided as agreed?','06A06-02','06A06','2','','','E2','12.6.1','10.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(956,'03','QUESTION','Is the respect of the security provisions by the suppliers or service providers under control and regularly reviewed?','06A06-03','06A06','4','','','E1','12.6.1','10.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(957,'04','QUESTION','Is it ensured that the suppliers report and document any security incident concerning information or networks?','06A06-04','06A06','4','','','E2','12.6.1','10.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(958,'05','QUESTION','Is there a regular review of these incidents or malfunctions with the concerned suppliers?','06A06-05','06A06','2','','','E2','12.6.1','10.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(959,'06','QUESTION','Are any changes in the contract relationship (e.g. Mandatory duties, service levels) analyzed for impact on resulting potential risks?','06A06-06','06A06','2','','','E3','15.2.2','10.2.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(960,'07','CATEGORY','Taking into account the confidentiality during maintenance operations on network equipment.','06A07','06A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(961,'01','QUESTION','Is there a procedure describing in detail the operations to execute before conducting maintenance thus avoiding their access to critical data (encryption keys, network protection, equipment security configuration, etc.)?','06A07-01','06A07','4','','','E2','11.2.4; 11.2.7','9.2.6; 9.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(962,'02','QUESTION','Is there a procedure or a contractual provision regarding the maintenance personnel (internal and external) specifying that any support containing sensitive information must be wiped out before its disposal?','06A07-02','06A07','4','','','E2','11.2.4','9.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(963,'03','QUESTION','Is there a systems` integrity verification procedure after a maintenance is conducted (no spyware, no Trojan horse, etc.)?','06A07-03','06A07','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(964,'04','QUESTION','Is a formal exemption, signed by a responsible manager, required if the above mentioned procedures are not observed? ','06A07-04','06A07','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(965,'05','QUESTION','Are the above procedures regularly audited?','06A07-05','06A07','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(966,'08','CATEGORY','Contract Management of Network Services','06A08','06A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(967,'01','QUESTION','Have service levels been identified for each network service?
Service levels apply not only to the services rendered to users, but also the security features required and the commitments of each party involved. ','06A08-01','06A08','4','','','E1','13.1.2','10.6.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(968,'02','QUESTION','Have these service levels been included in a contractual agreement  (whatever the services are ensured internally or by an external provider)?','06A08-02','06A08','4','','','E2','13.1.2','10.6.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(969,'03','QUESTION','Does Management control the application of corresponding measures?','06A08-03','06A08','2','','','C1','13.1.2','10.6.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(970,'06','CATEGORY','Parameters setting and control of hardware and software configurations','06B','06','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(971,'01','CATEGORY','Network equipment customizing and compliance control of configurations','06B01','06B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(972,'01','QUESTION','Is there a document or set of documents or an operational procedure detailing all security parameters for network equipment? which is derived from the network protection policy and determined filtering rules?
Such a document must result from the network protection policy and describe the filtering rules decided. It should also state the reference versions of the  systems so it is possible to check the status of the updates.','06B01-01','06B01','4','2','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(973,'02','QUESTION','Does this document (or documents) require the removal of all generic or by default accounts and does it detail the list of such accounts?  ','06B01-02','06B01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(974,'03','QUESTION','Does this document or procedure impose a synchronization feature, based on a reliable time reference?','06B01-03','06B01','4','','','E2','12.4.4','10.10.6'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(975,'04','QUESTION','Are these parameters set and updated regularly in line with latest information and in cooperation with expert authorities (specialized audits, subscription to a service center, regular consultation with CERTs, etc.)?
CERT : Computer Emergency Response Team.','06B01-04','06B01','2','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(976,'05','QUESTION','Are these referenced documents (or copies of installed parameters considered as references) protected, by secure sealing methods, against untimely or illicit alteration?  ','06B01-05','06B01','2','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(977,'06','QUESTION','Is the integrity of system configurations regularly tested against the configuration theoretically expected (at least weekly if not each time  systems are activated)?','06B01-06','06B01','4','2','','E3','18.2.3','15.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(978,'07','QUESTION','Are regular audits carried out of the list of security parameters specified?','06B01-07','06B01','2','','','R1','12.1.4; 18.2.3','10.1.4; 15.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(979,'08','QUESTION','Are regular audits carried out of the exception or escalation procedures in case of difficulties?','06B01-08','06B01','2','','','C1','12.1.4; 18.2.3','10.1.4; 15.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(980,'09','QUESTION','Are the development and test systems separated from the operational systems?','06B01-09','06B01','1','','','E2','12.1.4','10.1.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(981,'02','CATEGORY','Control of the network access configurations of  user equipment','06B02','06B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(982,'01','QUESTION','Is there a document detailing all parameters to check on user workstations related to external connections capability (modem, WiFi, etc.)?','06B02-01','06B02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(983,'02','QUESTION','Is this document regularly updated in line with the latest information and in cooperation with expert authorities (specialized audits, subscription to a service center, regular consultation with CERTs, etc.)?   ','06B02-02','06B02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(984,'03','QUESTION','Is this reference document protected against all unauthorized] or illicit modification by strong security methods (digital signature)?  ','06B02-03','06B02','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(985,'04','QUESTION','Is the configuration of network equipment of user workstations checked systematically for compliance against this reference document?','06B02-04','06B02','2','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(986,'05','QUESTION','Is this control effected systematically, at each connection to the network? ','06B02-05','06B02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(987,'06','QUESTION','Are there automatic routines which systematically analyze the use of the telephone network for data transmission? ','06B02-06','06B02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(988,'07','QUESTION','Are there automatic routines which test for the presence of non declared wireless network (WiFi) access points?  ','06B02-07','06B02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(989,'08','QUESTION','Are user workstations protected against the possibility of installing systems software and of modifying configurations? ','06B02-08','06B02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(990,'09','QUESTION','Is there a regular audit of the user configuration reference document and is the configuration control procedure regularly executed? ','06B02-09','06B02','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(991,'06','CATEGORY','Control of administrative rights ','06C','06','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(992,'01','CATEGORY','Control of special access rights to network equipment ','06C01','06C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(993,'01','QUESTION','Has a management policy for privileged access rights on the network equipment been established, based on prior analysis of the security requirements and business stakes?','06C01-01','06C01','2','','','E1','9.1.1','11.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(994,'02','QUESTION','Is this policy documented, regularly reviewed, and approved by the affected managers?','06C01-02','06C01','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(995,'03','QUESTION','Have profiles been defined, as part of network operations, corresponding to each type of activity (equipment administration, the administration of security equipment, network management, management of backup medias and contents etc.)?  ','06C01-03','06C01','1','','','E1','6.1.2; 9.2.3;  9.2.5; 13.1.1','10.1.3; 10.6.1; 11.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(996,'04','QUESTION','For each profile have the necessary administrative rights been defined? ','06C01-04','06C01','4','2','','E1','6.1.2; 13.1.1','10.1.3; 10.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(997,'05','QUESTION','Does the process of attribution of administrative rights require the formal authorization of management (or the manager responsible for external service providers) at a sufficiently high level?','06C01-05','06C01','4','2','','E2','6.1.2','10.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(998,'06','QUESTION','Does the process of attribution of administrative rights effected uniquely in relation to the profile of the holder?','06C01-06','06C01','4','2','','E2','6.1.2','10.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(999,'07','QUESTION','Is the process of granting (modification or retraction) of special rights to an individual strictly controlled?
A strict control requires a formal recognition of the signature (electronic or not) of the requester, that there be an access control in order to attribute or modify such rights and that any modification of special rights be logged and audited.','06C01-07','06C01','4','2','3','R1','9.2.3; 9.2.5','11.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1000,'08','QUESTION','Is there a systematic process of removal of administrative rights at the time of departure or role change of staff?','06C01-08','06C01','4','3','','E2','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1001,'09','QUESTION','Is there a regular audit, at least once a year, of all administrative rights attributed ?','06C01-09','06C01','1','2','','C1','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1002,'02','CATEGORY','Authentication of administrators and operational personnel  ','06C02','06C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1003,'01','QUESTION','Is the process of authentication of network administrators or holders of administrative rights considered to be secure?
An authentication protocol is considered secure if it is not susceptible to being broken by a listening device on the network or rendered inoperable by specialists tools (in particular password crack tools). Such security usually uses cryptographic methods.','06C02-01','06C02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1004,'02','QUESTION','Are the rules, for instance in the case of passwords, considered to be very strict?
Strict rules impose the use of tested non-trivial passwords and the use of a mixture of different types of character of a reasonable length (ten or more characters). It is desirable that such rules be decided or agreed upon by the CISO.','06C02-02','06C02','2','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1005,'03','QUESTION','Is a strong authentication used for the connection of administrators to the supervision system as well as for the connection of the supervision system to network equipments?
If the administrator connects to a hypervisor (such as HP OpenView, IBM TIVOLI, CA Unicenter, BMC Patrol or Bull OpenMaster) with secure authentication and effective access control, an equivalent level of security is needed for the objects that are managed (avoiding for example visible passwords, default public and community groups, access via telnet or simple SQL) in order to avoid malicious direct action on the equipment.','06C02-03','06C02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1006,'04','QUESTION','Is there a consistent control of the administrator`s rights, of its context, and of the suitability of this context with the requested access, as per formal rules of access control?','06C02-04','06C02','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1007,'05','QUESTION','Are authentication parameters under strict control?
A strict control requires that the list of people able to change authentication rules, the identifiers themselves and the rules for monitoring connection attempts be strictly limited, that there be a reinforced access control in order to be able to modify these rights and that any modification of these rights be logged and audited and that there be a general audit at least once a year of all authentication parameters.','06C02-05','06C02','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1008,'06','QUESTION','Are there processes that guarantee authentication under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (seal) and that there is an audit at least once a year of the authentication procedures and processes.','06C02-06','06C02','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1009,'07','QUESTION','Is there a regular audit of existing profiles having administrative rights?','06C02-07','06C02','4','3','','C1','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1010,'08','QUESTION','Is there a regular audit of the procedures for granting profiles and the security parameters protecting the profiles and the rights?','06C02-08','06C02','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1011,'03','CATEGORY','Surveillance of administrative actions on the network ','06C03','06C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1012,'01','QUESTION','Has a detailed analysis been carried out of the operations performed with administrative rights which may potentially have an impact on network security (configuration of security systems, access to sensitive information, usage of sensitive tools, download or modification of administrative tools etc.)?','06C03-01','06C03','2','','','E2','12.4.3; 13.1.1','10.10.4; 10.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1013,'02','QUESTION','Are all these events recorded on a log file as well as all parameters required for their subsequent analysis?','06C03-02','06C03','4','','','E2','12.4.3; 13.1.1','10.10.4; 10.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1014,'03','QUESTION','Is there a system which enables the detection of the modification or deletion of a past record and to immediately trigger an alarm to a manager? ','06C03-03','06C03','4','2','','E3','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1015,'04','QUESTION','Is there a summary of these records which enables management to detect abnormal behavior?','06C03-04','06C03','4','','3','E3','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1016,'05','QUESTION','Is there a system which enables the detection of any modification of recording parameters and to immediately trigger an alarm to a manager? ','06C03-05','06C03','4','2','','R1','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1017,'06','QUESTION','Does any inhibition of the recording system and processing of logged events trigger an alarm to a manager? ','06C03-06','06C03','4','3','','E3','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1018,'07','QUESTION','Are all records or summary analysis protected against destruction or modification?','06C03-07','06C03','2','','','R1','12.4.3','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1019,'08','QUESTION','Are all records or summary analysis kept for a long period?','06C03-08','06C03','2','','','R1','','10.10.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1020,'09','QUESTION','Are the procedures for recording and analyzing operations executed with administrative rights regularly audited? ','06C03-09','06C03','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1021,'04','CATEGORY','Control of networking operational tools and utilities ','06C04','06C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1022,'01','QUESTION','Is there an exhaustive inventory of the sensitive networking tools or utilities (administration of rights, configuration management, backups, copies, hot system restarts etc.) allowed for each type of operational staff profile?','06C04-01','06C04','4','','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1023,'02','QUESTION','Can the tools or sensitive utilities only be used by the holders of the corresponding profiles following a secure and individual authentication (authentication token, smart card etc.)?  ','06C04-02','06C04','2','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1024,'03','QUESTION','Is it forbidden to add or create tools or utilities without formal authorization?','06C04-03','06C04','2','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1025,'04','QUESTION','Is this forbidding rule regularly enforced by an automatic procedure which may trigger an alert to a manager? ','06C04-04','06C04','2','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1026,'05','QUESTION','Do the rights attributed to operational teams prohibit them from modifying operational tools and utilities or at the very least is there a control of any such modification with triggering of an alert to a manager? ','06C04-05','06C04','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1027,'06','QUESTION','Are the attribution of profiles and the implementation of the security measures mentioned above regularly audited?','06C04-06','06C04','2','2','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1028,'06','CATEGORY','Audit and Network Control Procedures','06D','06','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1029,'01','CATEGORY','Audit Control Operation ','06D01','06D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1030,'01','QUESTION','Has the management established the requirements and procedures to follow during the audits conducted on the networks?','06D01-01','06D01','4','','','E2','12.7.1','15.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1031,'02','QUESTION','Are the rules related to network audits, relevant procedures and associated responsibilities defined and documented?
The limits to be determined concern the type of access to the equipment, the controls and authorized processing, the deletion of sensitive data obtained, the flagging of certain operations, ... and the empowerment of the individuals conducting the audits. ','06D01-02','06D01','3','','','E2','12.7.1','15.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1032,'03','QUESTION','Are the auditors independent of the concerned activities?','06D01-03','06D01','2','','','E2','12.7.1','15.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1033,'04','QUESTION','Are the audit operations conducted for critical data recorded?','06D01-04','06D01','2','','','E3','12.7.1','15.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1034,'05','QUESTION','Are the possible actions of the auditors well delimited? 
Such limitations are recommended in the case of external auditors.','06D01-05','06D01','2','','','E2','','15.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1035,'02','CATEGORY','Protection of Tools and Audit Results','06D02','06D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1036,'01','QUESTION','Are the audit tools protected to avoid any unauthorized or abusive use?
This applies particularly to intrusion testing and vulnerability assessments.','06D02-01','06D02','3','','','E2','','15.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1037,'02','QUESTION','Are the audit results protected against any modification or disclosure?','06D02-02','06D02','3','','','E2','','15.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1038,'03','QUESTION','Is the use of audit tools and results strictly limited?
Such limitations are recommended in the case of external auditors.','06D02-03','06D02','2','','','E2','','15.3.2'); 
