INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1039,'07','QUESTIONNAIRE','MEHARI_SecurityAndArchitecture','07','','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1040,'07','CATEGORY','Control of access to systems ','07A','07','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1041,'01','CATEGORY','Management of access profiles (rights and privileges granted by functional profile) ','07A01','07A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1042,'01','QUESTION','Has a management policy for access rights to the systems been established, built from an analysis of the security requirements based on the business stakes?','07A01-01','07A01','2','','','E1','9.1.1','11.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1043,'02','QUESTION','Is access to the various parts of the information system (applications, data bases, systems, equipments, etc) defined in terms of job profiles which regroup roles or functions within the organization (profiles define access rights which are available to holders of the profile)?
Note: in certain circumstances the notion of profile may be replaced by the notion of group.','07A01-02','07A01','4','2','','E1','9.2.3; 9.2.5; 9.4.1','11.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1044,'03','QUESTION','Is it possible to adjust the access rights attributed to a given profile, based on the nature of the connection and equipment used (location, link, network, protocol, encryption, etc) and on the classification of the resources accessed?','07A01-03','07A01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1045,'04','QUESTION','Do the profiles also allow definition of working time limits (daily hours and periods in the working calendar, weekends, holidays etc.)?','07A01-04','07A01','2','','','E3','9.4.2','11.5.6'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1046,'05','QUESTION','Have these profiles and the access rights attributed to the different profiles, as a function of context, been approved by the information owners and the Information Security Officer?','07A01-05','07A01','4','2','','E2','9.4.2','11.5.6'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1047,'06','QUESTION','Is the process of definition and management of rights attributed to profiles under strict control?
A strict control requires that the list of people able to change rights attributed to profiles be strictly limited and that the implementation of these rights into tables be strictly secure during transmission and storage and that there exists a reinforced access control in order to be able to modify these rights and that any modification of these rights be logged and audited.','07A01-06','07A01','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1048,'07','QUESTION','Is it possible to review at any time, the complete list of profiles and of the rights attributed to each profile?  ','07A01-07','07A01','2','2','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1049,'08','QUESTION','Is there a regular audit at least once a year of all rights attributed to each profile and the profile management procedures?','07A01-08','07A01','4','2','','C1','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1050,'02','CATEGORY','Management of access authorizations and privileges (granting, delegation, revocation)','07A02','07A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1051,'01','QUESTION','Does the procedure of granting access authorization require the formal approval of line management (at a sufficiently high level)?','07A02-01','07A02','4','2','','E1','9.2.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1052,'02','QUESTION','Are authorizations granted to named individuals only as a function of their profile?','07A02-02','07A02','2','','','E1','9.2.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1053,'03','QUESTION','Is the procedure for granting (or changing or revoking) authorization to an individual (either directly or via his profile) strictly controlled?
A strict control requires a formal recognition of the signature (electronic or otherwise) of the requester, that the implementation of the profile attributed to users in the form of tables is highly secure during transmission and storage and that there be a reinforced access control over the modification of such records and that any modification of records be logged and audited.','07A02-03','07A02','4','2','3','E2','9.2.2; 9.2.5','11.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1054,'04','QUESTION','Is there a systematic process of updating the table of access authorizations at the time of departure of personnel (either internal or external)?','07A02-04','07A02','4','3','','E2','9.2.2; 9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1055,'05','QUESTION','Is there a systematic process of updating the table of access authorizations at the time of change of function?','07A02-05','07A02','4','','','E3','9.2.2; 9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1056,'06','QUESTION','Is there a strictly controlled process (as above) which allows to delegate his/her own authorizations, in part or in whole, to a person of choice for a determined period (in case of absence)?
In this case, the delegated rights must no longer be authorized to the person who has delegated them during this time. The owner however, must have the possibility of taking them back, by which process he or she effectively ends the delegation.','07A02-06','07A02','4','','','E3','9.2.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1057,'07','QUESTION','Is it possible to control at any time, for all users, the rights, authorizations and privileges in force?','07A02-07','07A02','2','','','C1','9.2.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1058,'08','QUESTION','Is there a regular audit, at least once a year, of  the profiles and authorizations granted to all users and of the procedures for management of attributed profiles?','07A02-08','07A02','1','2','','C1','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1059,'03','CATEGORY','Authentication of the access requester (user or entity)','07A03','07A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1060,'01','QUESTION','Does the process of distribution or modification of the user credentials guarantee that only the holder of the identifier can have access to them (initial communication is confidential, password change is under the exclusive control of the user, etc.)?  ','07A03-01','07A03','2','1','','E1','9.2.4; 9.4.3','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1061,'02','QUESTION','Does the process of definition or modification of user credentials respect a set of rules which ensures their intrinsic validity?
In the case of passwords: sufficient length (8 characters or more), obligatory mixture of types of characters, frequent change (less than once a month), impossibility of reusing an old password, non-trivial word test using a dictionary, banning of standard systems, first names, anagrams of user name, dates etc. In the case of certificates and authentications based on cryptographic mechanisms: generation process evaluated or publicly recognized, keys of a sufficient length etc.','07A03-02','07A03','4','2','','E2','9.2.4; 9.4.3','11.2.3; 11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1062,'03','QUESTION','Does the process of presenting a user password guarantee its trustworthiness?
The usage of a password will always be a weak point. The only process which does not divulge observable information consists of either introducing an object containing a secret (smart card), or entering a code which changes at every moment (token card type SecureId) or using a biometric characteristic.','07A03-03','07A03','4','2','','E3','9.2.4; 9.4.2;  9.4.3','11.5.1; 11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1063,'04','QUESTION','Is the logon process secured?
A secure logon should not give any information before the process is satisfactorily executed, not display the authenticators` password, display date and time of last connection, display eventual connection attempts that have failed, etc. ','07A03-04','07A03','1','','','E3','9.2.4; 9.4.2;  9.4.3','11.5.1; 11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1064,'05','QUESTION','Do the mechanisms for retention and usage of credentials by the user (or by the equipment representing the user) or by the target systems guarantee trustworthiness and authenticity of these credentials?
Passwords must be stored encrypted and a preliminary access control must be made before being accessible to the user.
In the case of authentication using cryptographic procedures, the mechanism must propose solid guarantees validated by a recognized organization.','07A03-05','07A03','2','2','3','E2','9.2.4; 9.4.2;  9.4.3','11.5.1; 11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1065,'06','QUESTION','Do the mechanisms used for the transmission of the credentials between the user and target equipments guarantee trustworthiness and authenticity of these credentials?
Transmission of a password must be encrypted or use an algorithm which introduces a variable at each transmission.
In the case of authentication using cryptographic procedures, the mechanism must propose solid guarantees validated by a recognized organization.','07A03-06','07A03','2','2','3','E3','9.4.2;  9.4.3','11.5.1; 11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1066,'07','QUESTION','In the case of multiple incorrect authentication attempts, is there an automatic process which temporarily invalidates the identifier used or, possibly, the user workstation itself, or which slows down the authentication process so as to inhibit any automatic routine from connecting?','07A03-07','07A03','4','2','','E2','9.4.2;  9.4.3','11.5.1; 11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1067,'08','QUESTION','Does the procedure for the replacement of a lost or mislaid user credential (password, token card) allow the instant deactivation of the old credential?','07A03-08','07A03','2','2','','E2','9.2.4','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1068,'09','QUESTION','Does the procedure for the replacement of a lost or mislaid user credential (password, token card) allow an effective control of the requester`s identity?','07A03-09','07A03','2','2','','E3','9.2.4','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1069,'10','QUESTION','Are authentication parameters under strict control?
A strict control requires that the list of people allowed to change the definition rules of credentials, the credentials themselves, the rules of surveillance of connection attempts etc., be strictly limited and that there exists a reinforced access control to effect these modifications, that these modifications be logged and audited and that there exists a regular general audit at least once a year of all authentication parameters.','07A03-10','07A03','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1070,'11','QUESTION','Are the processes that ensure authentication under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (close with a seal) and that there be an audit at least once a year of authentication procedures and processes (including the processes which aim to detect intrusion attempts and the processes which respond to these intrusion attempts).','07A03-11','07A03','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1071,'04','CATEGORY','Access filtering and management of associations ','07A04','07A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1072,'01','QUESTION','Does any access to a system require the use of an identifier recognized by the system?','07A04-01','07A04','1','2','','E1','','11.5.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1073,'02','QUESTION','Is there a direct or indirect correspondence between any identifier and a real physical person?
In the case where an application calls another or executes a system call, it may be that the application does not transfer to the target system the identifier which originally made the request. The link between the call, the identifier and the user himself must remain traceable after the fact.','07A04-02','07A04','4','2','','E1','','11.5.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1074,'03','QUESTION','Have all generic or by-default accounts been deleted?','07A04-03','07A04','4','2','','E2','','11.5.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1075,'04','QUESTION','Is the acceptance of the identifier by the system systematically subject to authentication?
Systematic authentication requires that the process be implemented for all subsystems (Remote process monitors, database management systems, batch processes, etc.), for all application requests and for all access routes, including ports reserved for remote maintenance.','07A04-04','07A04','2','2','','E2','9.4.2','11.5.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1076,'05','QUESTION','May the authentication process be renewed during an open session for those transactions considered to be sensitive?','07A04-05','07A04','4','','','E3','9.4.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1077,'06','QUESTION','Is there an automatic invalidation of the user session in the absence of traffic after a defined duration, thus requiring user re-identification and re-authentication?','07A04-06','07A04','4','','','E3','9.4.2','11.5.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1078,'07','QUESTION','Is there a systematic control, based upon definite access rules, of the profile of the requester, of the association context and of the appropriateness of that profile and context for the access requested?','07A04-07','07A04','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1079,'08','QUESTION','Are the parameters for the definition and management of access filtering rules under strict control?
A strict control requires that the list of persons allowed to change the security parameters for access filtering be extremely limited, and that there be a reinforced access control in order to be able to effect such modification and that any modification be logged and audited.','07A04-08','07A04','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1080,'09','QUESTION','Are the processes that guarantee access filtering under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (close with a seal) and that there be an audit at least once a year of access filtering procedures and processes (including the processes which aim to detect intrusion attempts and the processes which respond to these intrusion attempts).','07A04-09','07A04','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1081,'10','QUESTION','Are regular tests carried out to attempt to break into the information system and are there detailed technical audits run by specialists?','07A04-10','07A04','2','3','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1082,'05','CATEGORY','Authentication of the server for access to sensitive servers','07A05','07A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1083,'01','QUESTION','Is there a possibility to declare servers as sensitive and, as such, requiring an authentication of the server accessed?','07A05-01','07A05','4','1','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1084,'02','QUESTION','Is there a mechanism of authentication of the server called before access to a sensitive server from the internal network?','07A05-02','07A05','4','1','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1085,'03','QUESTION','Does the authentication mechanism of the accessed servers provide a recognized strong level of security?
Notably the usage of a simple password will always be a weakness. The only methods recognized as strong, that is observable without divulging information, are those based on cryptographic algorithms.','07A05-03','07A05','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1086,'04','QUESTION','Do the security equipment that retain credentials (e.g. passwords, calling number, etc.) use mechanisms which guarantee their impregnability and authenticity?
Passwords must be stored encrypted and a preliminary control of the user must be made before usage.
In the case of authentication using cryptographic procedures, the mechanism must provide solid guarantees validated by a recognized organization.','07A05-04','07A05','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1087,'05','QUESTION','Does the transmission of credentials (e.g. passwords, calling address, etc.) between calling user equipment and authentication systems use mechanisms which guarantee their impregnability and authenticity?
Transmission of a password must be encrypted or use an algorithm which introduces a variable at each transmission. 
In the case of authentication using cryptographic procedures, the mechanism must provide solid guarantees validated by a recognized organization.','07A05-05','07A05','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1088,'06','QUESTION','Does the revoked keys management procedure guarantee that the control systems take into consideration in real time any revocation of keys?','07A05-06','07A05','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1089,'07','QUESTION','Does the revoked keys management procedure guarantee that the control systems systematically test that the keys used have not been revoked?','07A05-07','07A05','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1090,'08','QUESTION','Are the processes that guarantee the authentication of the accessed entities under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (seal) and that there is an audit at least once a year of the authentication procedures and processes.','07A05-08','07A05','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1091,'07','CATEGORY','Containment of environments ','07B','07','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1092,'01','CATEGORY','Control of access to residual data','07B01','07B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1093,'01','QUESTION','Has a detailed analysis been carried out for each type of system to identify residual data files, their storage areas and access paths to such files and storage areas?','07B01-01','07B01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1094,'02','QUESTION','Have storage systems (and medias) been identified which once stored sensitive information and which have been re-affected to other usages? ','07B01-02','07B01','4','','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1095,'03','QUESTION','Does the system use an access rights control mechanism which prohibits user access to the contents of resources which have been freed up by another process (areas of memory, temporary resources )?  ','07B01-03','07B01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1096,'04','QUESTION','Are the tools which enable access to sensitive remnant data or temporary files reserved only for the use of systems operators and does access to those tools require a secure authentication?','07B01-04','07B01','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1097,'05','QUESTION','Are there procedures of physical erasure of residual files (in main memory or for storage media)?  ','07B01-05','07B01','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1098,'06','QUESTION','Are these procedures implemented systematically and automatically by the relevant systems each time a logical resource is freed? ','07B01-06','07B01','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1099,'07','QUESTION','Is the invalidation of such procedures alerted to an operational IT manager?','07B01-07','07B01','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1100,'08','QUESTION','Is there a procedure which guarantees that sensitive information contained on discarded media will be protected until the destruction of the supporting media?','07B01-08','07B01','4','','','E2','8.3.2','10.7.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1101,'09','QUESTION','Are all security procedures and parameters protecting access to residual data subject to regular audit?','07B01-09','07B01','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1102,'07','CATEGORY','Management and saving of logs ','07C','07','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1103,'01','CATEGORY','Recording access to sensitive resources ','07C01','07C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1104,'01','QUESTION','Has a specific analysis been carried out to determine which access requests and related parameters will be logged?','07C01-01','07C01','4','','','E2','12.4.1','10.10.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1105,'02','QUESTION','Is a tool or control application used which is able to log accesses to sensitive resources (applications, files, databases, etc.)?  ','07C01-02','07C01','4','','','E2','12.4.1','10.10.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1106,'03','QUESTION','Are the rules, specifying which accesses to log and retain, formalized?','07C01-03','07C01','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1107,'04','QUESTION','Have the rules, specifying which accesses to log and retain, been approved by the information owners or the Information Security Officer?','07C01-04','07C01','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1108,'05','QUESTION','Do the rules which specify which accesses will be logged include the necessary elements to carry out a subsequent investigation in the case of anomaly?
These rules should specify for each type of access (system, database management system, etc. ) the fundamental elements to record; for example user ID, the service or application requested, date and time, the point from where the access was requested if known etc.','07C01-05','07C01','2','','','E2','12.4.1','10.10.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1109,'06','QUESTION','Have these rules been validated by Legal Department (particularly for logs containing personal data)?','07C01-06','07C01','2','2','','E3','12.4.1','10.10.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1110,'07','QUESTION','Are all these records archived (on disk, cassettes, optical disk, etc.) and conserved for a long period in such a way as to not be modifiable?','07C01-07','07C01','2','','','E2','12.4.1; 12.4.2','10.10.1; 10.10.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1111,'08','QUESTION','Are the parameters for definition and management of recording connections (login) and called applications under strict control?
A strict control requires that the list of persons allowed  to change the definition parameters and the management of the recording rules for the logins and called applications be strictly limited and that there exist a reinforced access control to effect these modifications and that these modifications be logged and audited.','07C01-08','07C01','4','2','','R1','12.4.2','10.10.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1112,'09','QUESTION','Are the processes which ensure the recording of connections and called applications under strict control?
A strict control requires that the software used for recording has been validated and undergoes a regular test for integrity (closed with seal) and that there be an audit at least once a year of recording procedures and processes (including the processes which aim to detect modification attempts and the processes which respond to these modification attempts).','07C01-09','07C01','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1113,'02','CATEGORY','Recording privileged system calls ','07C02','07C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1114,'01','QUESTION','Has a specific analysis been carried out of privileged system calls to log and of parameters related to these calls which should be recorded?','07C02-01','07C02','4','','','E2','12.4.1','10.10.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1115,'02','QUESTION','Is use made of a tool or control application which is able to record privileged system calls (tools which require special access rights, access to security files, administration of security parameters etc.)?','07C02-02','07C02','4','','','E2','12.4.1','10.10.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1116,'03','QUESTION','Have the rules specifying the privileged system calls to be logged been formalized?','07C02-03','07C02','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1117,'04','QUESTION','Have the rules specifying the privileged system calls to be logged been approved by the information owners or the Information Security Officer?','07C02-04','07C02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1118,'05','QUESTION','Do the rules specifying the accesses to privileged system calls to be logged include the relevant elements needed for subsequent investigation in the case of anomaly?
The rules must specify for each type of system call (create, read, update or delete) the basic elements to record, for example, the nature of the event, the user identifier, the systems services required, date and time etc.','07C02-05','07C02','2','','','E2','12.4.1','10.10.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1119,'06','QUESTION','Have these rules been validated by Legal Department (particularly for logs containing personal data)?','07C02-06','07C02','2','2','','E3','12.4.1','10.10.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1120,'07','QUESTION','Are all these records archived (on disk, cassettes, optical disk, etc.) and conserved for a long period in such a way as to not be falsifiable?','07C02-07','07C02','2','','','E2','12.4.1; 12.4.2','10.10.3; 10.10.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1121,'08','QUESTION','Are the parameters for definition and management of the rules for recording privileged system calls under strict control?
A strict control requires that the list of persons allowed to change the recording parameters be strictly limited and that there exists a reinforced access control to effect these modifications and that these modifications be logged and audited.','07C02-08','07C02','4','2','','R1','12.4.2','10.10.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1122,'09','QUESTION','Are the processes which ensure the recording of privileged system calls under strict control?
A strict control requires that the software used for recording has been validated and undergoes a regular test for integrity (closed with seal) and that there be an audit at least once a year of recording procedures and processes (including the processes which aim to detect modification attempts and the processes which respond to these modification attempts).','07C02-09','07C02','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1123,'07','CATEGORY','Security of the architecture','07D','07','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1124,'01','CATEGORY','Service continuity of the architecture and of its components','07D01','07D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1125,'01','QUESTION','Has an analysis been carried out of the various shared equipment and systems (apart from the architecture of the applications but including general peripheral systems such as backup systems and robots, print servers and centralized printing equipment) in order to highlight the needs of service continuity?
An in depth analysis assumes that a list of failure scenarios has been established and that the consequences of such events have been analyzed.','07D01-01','07D01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1126,'02','QUESTION','Has this analysis allowed to detail the minimum performance levels that must be maintained for each system and have these performance levels been accepted by users or information owners?','07D01-02','07D01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1127,'03','QUESTION','Has the appropriate level of architectural redundancy been determined (e.g. clusters or disk replication ) for the servers or equipment concerned? ','07D01-03','07D01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1128,'04','QUESTION','Does the architecture and its implementation guarantee that the minimum performance levels will be exceeded in the case of an incident of failure?
Such a guarantee supposes that either fail safe systems are entirely automatic or that sufficient detection systems and staff are in place so as to manually reconfigure them.','07D01-04','07D01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1129,'05','QUESTION','Is there an assurance in this case that secondary equipment (power supply, air-conditioning, etc. ) does not introduce any additional risk and does not eliminate redundancy envisaged for the systems architecture or equipment?','07D01-05','07D01','2','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1130,'06','QUESTION','Does any shutdown or inhibition of redundant equipment or system devoted to detecting the need for human intervention or for automatic reconfiguration trigger an alarm to an operational manager? ','07D01-06','07D01','2','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1131,'07','QUESTION','Are regular tests made to demonstrate that security equipment is able to guarantee minimum performance levels required in the case of an incident or failure? ','07D01-07','07D01','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1132,'02','CATEGORY','Isolation of Sensitive Systems','07D02','07D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1133,'01','QUESTION','Has the systems` sensitivity been analyzed (based on the applications and data processed) including peripheral systems or robots used for storage or archiving, print servers or central printing equipment, etc.) to highlight their security requirements?
A thorough analysis implies the establishment of a list of incident scenarios (A, I, C), for which all foreseeable consequences were analyzed.','07D02-01','07D02','3','','','E2','','11.6.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1134,'02','QUESTION','Did this analysis allow to formalize minimum requirements for each system and were these minimum requirements accepted by the users (information owner)?','07D02-02','07D02','3','','','E2','','11.6.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1135,'03','QUESTION','Have appropriate isolation measures (physical and logical) been determined for these servers and equipment?
These measures may impose to use different data centers for sensitive servers or applications from other servers.','07D02-03','07D02','3','','','E2','','11.6.2'); 
