INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1513,'09','QUESTIONNAIRE','MEHARI_ApplicationSecurity','09','','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1514,'09','CATEGORY','Application access control ','09A','09','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1515,'01','CATEGORY','Management of application data access profiles ','09A01','09A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1516,'01','QUESTION','Has a management policy for access rights to data and information been established, built from an analysis of the security requirements based on the business stakes?','09A01-01','09A01','2','','','E1','9.1.1','11.1.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1517,'02','QUESTION','Is access to applications and associated data defined in terms of job profiles which regroup roles or functions within the organization (a profile defines access rights available  to holders of the profile)?
Note: in certain circumstances the notion of profile may be replaced by the notion of group.','09A01-02','09A01','4','2','','E1','9.2.3; 9.2.5; 9.4.1','11.2.2; 11.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1518,'03','QUESTION','Is it possible to adjust the access rights (that establish rights attributed to a given profile), variable parameters based on the connection context such as the origin of the request or network paths used, or depending on protection means used (protocol, encryption, etc) and on the classification of the resources accessed?','09A01-03','09A01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1519,'04','QUESTION','Do the access profiles also allow definition of working time limits and periods in the working calendar (daily hours, weekends, holidays etc.)?','09A01-04','09A01','2','','','E3','9.4.2','11.5.6'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1520,'05','QUESTION','Have these profiles and the access rights attributed to the different profiles been approved by the information owners and/or the Information Security Officer?','09A01-05','09A01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1521,'06','QUESTION','Are the processes of definition and management of rights attributed to profiles under strict control?
A strict control requires that the list of people allowed to change rights attributed to profiles be strictly limited and that the implementation of these rights (e.g. into tables) be strictly secure and that there exist a reinforced access control for any modification of these rights and that any modification be logged and audited.','09A01-06','09A01','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1522,'07','QUESTION','Is it possible to review at any time the list of profiles and the rights attributed to each profile?','09A01-07','09A01','2','2','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1523,'08','QUESTION','Is there a regular audit, at least once a year, of the totality of rights attributed to each profile and the profile management procedures?','09A01-08','09A01','4','2','','C1','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1524,'02','CATEGORY','Management of access authorizations to application data (granting, delegation, revocation) ','09A02','09A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1525,'01','QUESTION','Does the procedure of granting access authorization to applications require the formal authorization of line management  (at a sufficiently senior level)?','09A02-01','09A02','4','2','','E1','9.4.1','11.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1526,'02','QUESTION','Are authorizations granted to named individuals and only as a function of their profile?','09A02-02','09A02','2','','','E1','','11.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1527,'03','QUESTION','Is the procedure for granting (or modification or revocation) of access rights (directly or via a profile) strictly controlled?
A strict control requires a formal recognition of the signature (electronic or otherwise) of the requester, that the implementation of the profile attributed to users in the form of tables is highly secure and that there be a reinforced access control over the modification of such records and that any modification of records be logged and audited.','09A02-03','09A02','4','2','3','E2','9.2.3','11.2.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1528,'04','QUESTION','Is there a systematic process of updating the table of access rights at the time of departure of personnel (internal or external personnel)?','09A02-04','09A02','4','','','E2','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1529,'05','QUESTION','Is there a systematic process of updating the table of access rights at the time of change of function?','09A02-05','09A02','4','','','E3','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1530,'06','QUESTION','Is there a strictly controlled process (see below) which allows rights to be delegated, in part or in whole, to a person of choice for a determined period (in case of absence)?
In this case, the delegated rights must no longer be available to the person who has delegated them during this time. The latter however, must have the possibility of taking them back, by which process he or she effectively ends the delegation.','09A02-06','09A02','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1531,'07','QUESTION','Is it possible to control at any time, for all users, the rights, authorizations and privileges in force?','09A02-07','09A02','2','','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1532,'08','QUESTION','Is there a regular audit, at least once a year, of the profiles and authorizations granted to all personnel and the procedures for management of attributed profiles?','09A02-08','09A02','1','2','','C1','9.2.5','11.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1533,'03','CATEGORY','Authentication of the access requester','09A03','09A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1534,'01','QUESTION','Does the process of distribution or modification of the user credentials guarantee that only the holder of the identifier has access (initial communication is confidential, password change is under the exclusive control of the user, etc.)?  ','09A03-01','09A03','2','1','','E1',' 9.4.3','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1535,'02','QUESTION','Does the process of creation or modification of a user credentials respect a set of rules which ensures its intrinsic validity?
In the case of passwords: sufficient length (8 characters or more), obligatory mixture of types of characters, frequent change (less than once a month), impossibility of reusing an old password, non-trivial word test using a dictionary, banning of standard systems, first names, anagrams of user name, dates etc.
In the case of certificates or use made of cryptographic mechanisms for authentication: a generation process evaluated or publicly recognized, encryption keys of a sufficient length etc.','09A03-02','09A03','4','2','','E2',' 9.4.3','11.2.3; 11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1536,'03','QUESTION','Does the presentation of his credentials by the user guarantee their inviolability?
Typing a password will always be a weak point. The only processes whose observation does not divulge information consist either of introducing an object containing a secret (smart card), or using a code which changes at every moment (token card) or using a means of which contains some biometric characteristic.','09A03-03','09A03','4','2','','E3',' 9.4.3','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1537,'04','QUESTION','Is there a guarantee that the credentials, used for authentication, will remain inviolable and authentic while kept or presented by the user or by the user agent?
Passwords must be stored encrypted and a preliminary access control must be made before usage. 
In the case of authentication using cryptographic processing, the mechanism must provide solid guarantees validated by a reference organization.','09A03-04','09A03','2','2','3','E2',' 9.4.3','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1538,'05','QUESTION','Is there a guarantee that the credentials, used for authentication, will remain inviolable and authentic while transmitted between the user and the target systems?
Transmission of a password must be encrypted or use an algorithm which introduces a variable at each transmission. 
In the case of authentication using cryptographic processing, the mechanism must provide solid guarantees validated by a reference organization.','09A03-05','09A03','2','2','3','E3',' 9.4.3','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1539,'06','QUESTION','In the case of multiple incorrect authentication attempts, is there a process which automatically invalidates the user identifier, even the user workstation itself, or a slowing of the authentication process (aimed at preventing connection from an automatic routine)?','09A03-06','09A03','4','2','','E2',' 9.4.3','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1540,'07','QUESTION','Does the procedure for the replacement of lost or mislaid user authentication means (password, token card) allow for the instant deactivation of the user account?','09A03-07','09A03','2','2','','E2',' 9.4.3','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1541,'08','QUESTION','Does the procedure for the replacement of lost or mislaid user authentication means (password, token card) allow for an effective control of the requester`s identity?','09A03-08','09A03','2','2','','E3',' 9.4.3','11.5.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1542,'09','QUESTION','Are authentication parameters under strict control?
A strict control requires that people able to change the definition rules of credentials, the credentials themselves, rules of surveillance of connection attempts etc., be strictly limited and that there exists a reinforced access control to effect these modifications, that these modifications be logged and audited and that a general audit be run at least once a year of all authentication parameters.','09A03-09','09A03','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1543,'10','QUESTION','Are the processes that guarantee authentication under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (seal) and that there be an audit at least once a year of authentication procedures and processes (including the processes which aim to detect violations attempts and the processes which respond to these violation attempts).','09A03-10','09A03','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1544,'04','CATEGORY','Access filtering and management of associations ','09A04','09A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1545,'01','QUESTION','Does any access to the system require the use of an identifier recognized by the system?','09A04-01','09A04','1','2','','E1','9.4.1','11.5.2; 11.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1546,'02','QUESTION','Is there a direct or indirect correspondence between any identifier and a real physical person?
In the case where an application calls another one or calls a system, it may be that the application does not transfer to the target system the identifier which originally made the request. However, the link between that call and the original user identifier must remain traceable after the fact.','09A04-02','09A04','4','2','','E1','9.4.1','11.5.2; 11.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1547,'03','QUESTION','Have all generic or by-default accounts and passwords been changed or deleted?','09A04-03','09A04','4','2','','E2','','11.5.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1548,'04','QUESTION','Is the acceptance of the account identified by the system systematically followed by authentication control?
Systematic authentication requires that the process be implemented for all subsystems (remote processing monitor, database management system, batch processes, etc. ), for all application requests, for all access routes and for all ports, including ports reserved for remote maintenance.','09A04-04','09A04','2','2','','E2','','11.5.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1549,'05','QUESTION','May the authentication process be repeated during an open session for transactions considered to be sensitive?','09A04-05','09A04','4','','','E3','9.4.2','11.5.6'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1550,'06','QUESTION','Is there an automatic invalidation of the user identifier in the absence of traffic after a defined delay, which requires user re-identification and re-authentication?','09A04-06','09A04','4','','','E3','9.4.2','11.5.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1551,'07','QUESTION','Are there application access controls which limit the view and access to very sensitive information?','09A04-07','09A04','4','','','E3','9.4.1','11.6.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1552,'08','QUESTION','Is there a systematic control of the profile and connection context of the requester and of their appropriateness for the access requested?','09A04-08','09A04','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1553,'09','QUESTION','Is the process of definition and management of access filtering rules under strict control?
A strict control requires that the list of persons able to change the filtering security parameters be extremely limited, and that there be a reinforced access control in order to be able to effect such modification and that any modification be logged an audited.','09A04-09','09A04','4','2','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1554,'10','QUESTION','Are the processes that guarantee access filtering under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (seal) and that there be an audit at least once a year of access control procedures and processes (including the processes which aim to detect change attempts and the processes which respond to these change attempts).','09A04-10','09A04','4','3','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1555,'05','CATEGORY','Authentication of the application for access to sensitive applications','09A05','09A','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1556,'01','QUESTION','Is there a possibility to declare applications as sensitive and, as such, requiring an authentication of the application accessed?','09A05-01','09A05','4','1','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1557,'02','QUESTION','Is there a mechanism of authentication of the application called before access to a sensitive application from the internal network?','09A05-02','09A05','4','1','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1558,'03','QUESTION','Does the authentication mechanism of the accessed sensitive applications provide a recognized strong level of security?
Notably the usage of a simple password will always be a weakness. The only methods recognized as strong, that is observable without divulging information, are those based on cryptographic algorithms.','09A05-03','09A05','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1559,'04','QUESTION','Do the security equipment that retain credentials (e.g. passwords, calling number, etc.) use mechanisms which guarantee their impregnability and authenticity?
Passwords must be stored encrypted and a preliminary control of the user must be made before usage.
In the case of authentication using cryptographic procedures, the mechanism must provide solid guarantees validated by a recognized organization.','09A05-04','09A05','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1560,'05','QUESTION','Does the transmission of credentials (e.g. passwords, calling address, etc.) between calling user equipment and authentication systems use mechanisms which guarantee their impregnability and authenticity?
Transmission of a password must be encrypted or use an algorithm which introduces a variable at each transmission. 
In the case of authentication using cryptographic procedures, the mechanism must provide solid guarantees validated by a recognized organization.','09A05-05','09A05','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1561,'06','QUESTION','Does the revoked keys management procedure guarantee that the control systems take into consideration in real time any revocation of keys?','09A05-06','09A05','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1562,'07','QUESTION','Does the revoked keys management procedure guarantee that the control systems systematically test that the keys used have not been revoked?','09A05-07','09A05','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1563,'08','QUESTION','Are the processes that guarantee the authentication of the accessed entities under strict control?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (seal) and that there is an audit at least once a year of the authentication procedures and processes.','09A05-08','09A05','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1564,'09','CATEGORY','Control of data integrity ','09B','09','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1565,'01','CATEGORY','Sealing of sensitive data ','09B01','09B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1566,'01','QUESTION','Have integrity sensitive files been identified which must be protected by sealing solutions and have such solutions been implemented at the application level?','09B01-01','09B01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1567,'02','QUESTION','Are the seals controlled automatically by the corresponding applications?','09B01-02','09B01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1568,'03','QUESTION','Does the sealing solution offer valid and solid guarantees and has it been approved by the Information Security Officer?
The sufficient length of the key is one of the parameters to take into consideration. The recommendation of an official organization can be a confidence factor.','09B01-03','09B01','4','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1569,'04','QUESTION','Do the procedures and mechanisms for storage, distribution and exchange of keys and more generally the management of keys offer a sufficient level of confidence and have they been approved by the Information Security Officer?','09B01-04','09B01','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1570,'05','QUESTION','Are the sealing mechanisms strictly protected against violation or change?
In the case of hardware sealing and appliances, they should be physical protected against access to the sealing mechanisms. If a software solution is used, it must itself contain an integrity control.','09B01-05','09B01','4','3','3','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1571,'06','QUESTION','Is shutdown or by-pass of the sealing solution immediately detected and signaled to a team available 24 hrs a day and capable of triggering an immediate reaction?','09B01-06','09B01','4','2','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1572,'07','QUESTION','Is there a procedure detailing the actions to carry out in the case of error or alert?','09B01-07','09B01','3','','2','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1573,'08','QUESTION','Are sealing mechanisms, their parameters and associated procedures subject to regular audit?','09B01-08','09B01','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1574,'02','CATEGORY','Protection of integrity of exchanged data ','09B02','09B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1575,'01','QUESTION','Have all data exchanges which must be protected by sealing solutions been defined and have such solutions been implemented at the application level?','09B02-01','09B02','4','','','E2','','12.2.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1576,'02','QUESTION','Are the seals controlled automatically by the corresponding applications?','09B02-02','09B02','4','2','','E3','','12.2.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1577,'03','QUESTION','Does the sealing solution offer valid and solid guarantees and has it been approved by the Information Security Officer?
The sufficient length of the key is one of the parameters to take into consideration (as a function of the algorithm). The recommendation of an official organization can be a confidence factor.','09B02-03','09B02','4','2','','E2','','12.2.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1578,'04','QUESTION','Do the procedures and mechanisms for storage, distribution and exchange of keys and more generally the management of keys offer a sufficient level of confidence and have they been approved by the Information Security Officer?','09B02-04','09B02','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1579,'05','QUESTION','Are the sealing mechanisms strictly protected against violation or change?
In the case of hardware sealing and appliances, they should be physical protected against access to the sealing mechanisms. If a software solution is used, it must itself contain an integrity control.','09B02-05','09B02','4','3','3','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1580,'06','QUESTION','Is shutdown or by-pass of the sealing solution immediately detected and signaled to a team available 24 hrs a day or by direct call and capable of triggering an immediate reaction?','09B02-06','09B02','4','2','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1581,'07','QUESTION','Is there a procedure detailing the actions to carry out in the case of error or alert?','09B02-07','09B02','3','','2','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1582,'08','QUESTION','Are sealing mechanisms, their parameters and associated procedures subject to regular audit?','09B02-08','09B02','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1583,'03','CATEGORY','Control of data entry ','09B03','09B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1584,'01','QUESTION','Are sensitive data strictly controlled by the person entering them (auto-control)?','09B03-01','09B03','2','','','E1','','12.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1585,'02','QUESTION','Are sensitive data subject to data entry control by another person?','09B03-02','09B03','4','2','','E1','','12.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1586,'03','QUESTION','Are sensitive data subject to means allowing to ascribe their entry or modification to their author?','09B03-03','09B03','4','','','E3','','12.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1587,'04','QUESTION','Are there incentives for data entry without error (individual bonuses, departmental bonuses, penalties in the case of too many errors etc.)?  ','09B03-04','09B03','2','','','E2','','12.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1588,'05','QUESTION','Is there an overall control of series of data items entered (sum, range, min, max, etc.)?  ','09B03-05','09B03','4','','','E2','','12.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1589,'06','QUESTION','Is data entry subject to coherence checks incorporated into the data entry process?','09B03-06','09B03','4','','','E2','','12.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1590,'07','QUESTION','Are these additional checks (range, coherence, etc.) strongly protected against any illicit alteration ?  ','09B03-07','09B03','4','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1591,'08','QUESTION','Have the procedures to correct data entry errors been defined?','09B03-08','09B03','4','','','R1','','12.2.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1592,'09','QUESTION','Is the checking process subject to regular audit?','09B03-09','09B03','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1593,'04','CATEGORY','Permanent checks (accuracy, etc) relating to data','09B04','09B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1594,'01','QUESTION','Has a review been carried out with users to determine suitable controls of the pertinence of data entered or modified (correction in relation to data ranges, ratios between data entered independently, coherence checks, evolution and comparison with statistics) and have the corresponding controls been implemented in applications?','09B04-01','09B04','4','','','E1','','12.2.1; 12.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1595,'02','QUESTION','Have control parameters (values of data ranges, etc.) been stored in tables separate from the application and which may be easily checked?','09B04-02','09B04','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1596,'03','QUESTION','Are the processes that guarantee these permanent controls under strict control themselves?
A strict control requires that the software used has been validated and undergoes a regular test for integrity (seal) and that there is an audit at least once a year of the control procedures and processes.','09B04-03','09B04','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1597,'04','QUESTION','Are the parameters of permanent controls under strict control?
A strict control requires that the list of people able to change control parameters be strictly limited and that there be a reinforced access control in order to be able to modify these parameters and that any modification of these parameters be logged and audited.','09B04-04','09B04','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1598,'05','QUESTION','When these controls exist, are they the integrated into an operational process for alert and processing of errors?','09B04-05','09B04','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1599,'05','CATEGORY','Continuous (plausibility, ..) checks on data processing ','09B05','09B','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1600,'01','QUESTION','Have the checks that should be made to verify consistency of the data after processing by the application been analyzed with the users (test variables, ratios, evolution and comparison before and after processing, etc.), and have the corresponding checks been implemented in the applications?','09B05-01','09B05','4','','','E1','','12.2.1; 12.2.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1601,'02','QUESTION','Are the parameters for these checks recorded in tables separated from the application code and easily verifiable?','09B05-02','09B05','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1602,'03','QUESTION','Are the processes insuring continuous checking of the data processing under strict control?
Strict control requires that the corresponding software is validated and is subject to a regular integrity check (sealing)  and that there is an audit at least once a year of the control process and procedures (including procedures for detecting attempts at modification and for reacting to these attempts).','09B05-03','09B05','4','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1603,'04','QUESTION','Are the check parameters under strict control?
Strict control requires that the list of people authorized to change the control parameters is very limited, that strong access control is applied to all modifications, and that the modifications are logged and audited. ','09B05-04','09B05','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1604,'05','QUESTION','Are the checks that exist integrated into an operational procedure that signals and handles any errors? ','09B05-05','09B05','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1605,'09','CATEGORY','Control of data confidentiality ','09C','09','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1606,'01','CATEGORY','Encryption of data exchanges 
Here we consider the encryption effected directly by the application (ISO layers 6-7, prior to or during transmission).','09C01','09C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1607,'01','QUESTION','Have the messages which must be protected by encryption solutions been defined and such solutions been implemented at the application level?','09C01-01','09C01','4','','','E1','10.1.1','12.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1608,'02','QUESTION','Does the encryption solution offer valid and solid guarantees and has it been approved by the Information Security Officer?
The sufficient length of the key is one of among many parameters to take into consideration (as a function of the algorithm). The recommendation of an official organization can be a confidence factor.','09C01-02','09C01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1609,'03','QUESTION','Does the procedure and mechanisms of storage, distribution and exchange of keys and more generally the management of the keys offer solid guarantees which merit confidence and are they approved by the Information Security Officer?','09C01-03','09C01','4','3','','E2','10.1.2','12.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1610,'04','QUESTION','Are the encryption mechanisms strictly protected against violation or change?
In the case of hardware encryption and appliances, they should be physical protected against access to the encryption mechanisms. If a software solution is used, it must itself contain an integrity control.','09C01-04','09C01','4','3','3','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1611,'05','QUESTION','Is shutdown or by-pass of the encryption solution immediately detected and signaled to a team available 24 hrs a day or by direct call and capable of triggering an immediate reaction?','09C01-05','09C01','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1612,'06','QUESTION','Are encryption mechanisms, their parameters and associated procedures subject to regular audit?','09C01-06','09C01','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1613,'02','CATEGORY','Encryption of stored data ','09C02','09C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1614,'01','QUESTION','Have the files or storage zones which must be protected by encryption solutions been defined and have such solutions been implemented in the application architecture?','09C02-01','09C02','4','','','E1','10.1.1','12.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1615,'02','QUESTION','Is this encryption systematically applied (as a function of information classification ) and/or automatic (as a function of storage media) each time data is written to the storage media or each time the application session closes?','09C02-02','09C02','2','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1616,'03','QUESTION','Is this encryption systematically applied each time files are transferred or remotely-loaded by the relevant applications?','09C02-03','09C02','2','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1617,'04','QUESTION','Does the encryption solution offer valid and solid guarantees and has it been approved by the Information Security Officer?
The sufficient length of the key is one of among many parameters to take into consideration (as a function of the algorithm). The recommendation of an official organization can be a confidence factor.','09C02-04','09C02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1618,'05','QUESTION','Do the procedures and mechanisms for storage, distribution and, more generally, management of keys offer a sufficient level of confidence and have they been approved by the Information Security Officer?
The possibility of having to recover these data on another hardware system or another version of the operating system needs to be anticipated.','09C02-05','09C02','4','3','','E2','10.1.2','12.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1619,'06','QUESTION','Are the encryption mechanisms strictly protected against intrusion or change?
In the case of hardware encryption and appliances, they should be physical protected against access to the encryption mechanisms. If a software solution is used, it must itself contain an integrity control.','09C02-06','09C02','4','3','3','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1620,'07','QUESTION','Is shutdown or by-pass of the encryption solution immediately detected and signaled to a team available 24 hrs a day or by direct call and capable of triggering an immediate reaction?','09C02-07','09C02','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1621,'08','QUESTION','Are encryption mechanisms for stored data, their parameters and associated procedures (in particular the management and protection of keys) subject to regular audit?','09C02-08','09C02','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1622,'03','CATEGORY','Anti electromagnetic radiation protection','09C03','09C','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1623,'01','QUESTION','Are means used to prevent radiation from equipment hosting very sensitive applications (Tempest, cable shielding, faradizations of the offices)?','09C03-01','09C03','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1624,'02','QUESTION','Are radiation levels regularly controlled for equipment hosting these sensitive applications?','09C03-02','09C03','2','2','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1625,'09','CATEGORY','Data availability','09D','09','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1626,'01','CATEGORY','Very high security recording','09D01','09D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1627,'01','QUESTION','Are specific procedures applied to verify that all data recorded can be reread?','09D01-01','09D01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1628,'02','QUESTION','Are there procedures or an architecture of a very high security level which records all data with redundancy (RAID disks, mirroring, etc.)?  ','09D01-02','09D01','4','','3','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1629,'03','QUESTION','Do these very high security procedures enable the reconstitution of data in the case of an error or readability issue for a few sectors?','09D01-03','09D01','4','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1630,'04','QUESTION','Have scenarios been defined for which very high security recording is to be used and has the physical protection of storage media been tested to ensure that it is suited to meet the requirements of these scenarios?','09D01-04','09D01','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1631,'02','CATEGORY','Management of access to data files','09D02','09D','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1632,'01','QUESTION','Is the list of data file formats that must be readable verified and maintained? ','09D02-01','09D02','4','3','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1633,'02','QUESTION','Are the hardware and software required for reading all these types of data files available or easily made available?','09D02-02','09D02','4','3','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1634,'03','QUESTION','Do the procedures for allocating and customizing the mechanisms for encryption and protection of files guarantee that the files can be accessed, even in the event of the absence or departure of the file owners? ','09D02-03','09D02','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1635,'04','QUESTION','Are the means of recovering access keys or encryption keys protected against accidental or malicious loss?','09D02-04','09D02','4','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1636,'05','QUESTION','Are there regular audits of these means and procedures to guarantee permanent access to the data files? ','09D02-05','09D02','2','3','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1637,'09','CATEGORY','Service continuity','09E','09','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1638,'01','CATEGORY','Hardware reconfiguration','09E01','09E','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1639,'01','QUESTION','Has a fail-safe architecture been established, including redundancy and system mirroring for critical equipment or servers?','09E01-01','09E01','4','2','','E2','','14.1.4'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1640,'02','QUESTION','Does the implementation of this architecture guarantee the minimum performance levels required in the case of incident or failure?
Such a guarantee supposes either that fail safe systems features are entirely automatic or that systems will detect failures and staff will have the specifications and capability to manually reconfigure failed systems.','09E01-02','09E01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1641,'03','QUESTION','Is there some assurance in this case that ancillary equipment (power supply, air-conditioning, etc. ) do not introduce any additional risk and do not ruin the redundancy expected from the equipment or network architecture?','09E01-03','09E01','2','','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1642,'04','QUESTION','Does the shutdown or invalidation of any redundant equipment or failure detection system (requiring human intervention) trigger an alarm to an operational manager? ','09E01-04','09E01','2','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1643,'05','QUESTION','Are regular tests made to demonstrate that security equipment is able to guarantee minimum performance levels required in the case of an incident or failure? ','09E01-05','09E01','2','2','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1644,'02','CATEGORY','Application service continuity plans','09E02','09E','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1645,'01','QUESTION','Have application service continuity plans been established for each business application, based on its criticality classification level?','09E02-01','09E02','3','','','E1','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1646,'02','QUESTION','Are these continuity plans compatible with the Disaster Recovery Plans for the hardware and systems used by the process or application?','09E02-02','09E02','3','2','','E1','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1647,'03','QUESTION','Do these continuity plans detail all the actions necessary to ensure service continuity between the time of an alert and the effective implementation of solutions prescribed by the Disaster Recovery Plans?','09E02-03','09E02','3','2','','E2','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1648,'04','QUESTION','Do these plans treat all the organizational aspects related to a manual emergency solution (personnel, logistic, management etc.)?','09E02-04','09E02','3','','','E2','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1649,'05','QUESTION','Have the appropriate instructions and training been given to staff in order to deal with a manual emergency solution?','09E02-05','09E02','2','','','E2','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1650,'06','QUESTION','Have the application service continuity plans anticipated all the procedures required for a return to normal service?','09E02-06','09E02','4','2','','E2','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1651,'07','QUESTION','Is there a plan which regroups all emergency solutions designed to overcome critical process and application shutdowns?','09E02-07','09E02','4','','','E2','17.1.2','14.1.3'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1652,'08','QUESTION','Is the crisis plan initiation compliant with the above application service continuity plan?','09E02-08','09E02','4','','','E2','17.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1653,'09','QUESTION','Are these plans regularly tested under full scale conditions (with operational data volumes) and updated at least once a year?','09E02-09','09E02','3','2','','C1','17.1.2; 17.1.3','14.1.5'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1654,'10','QUESTION','Are the updates of these plans regularly audited (at least once a year)?  ','09E02-10','09E02','3','2','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1655,'03','CATEGORY','Management of critical applications (with regard to maintenance continuity)','09E03','09E','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1656,'01','QUESTION','Have the consequences of the disappearance of an application or package editor been analyzed (in the case of failure of a bug or the need for evolution) and has a list of critical applications been deduced? ','09E03-01','09E03','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1657,'02','QUESTION','For each critical application, is there a corrective solution to cope with the failure or disappearance of a supplier (consignment of maintenance documentation and source code with a trusted third party, replacement of equipment or of software by standard package etc.)?','09E03-02','09E03','2','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1658,'03','QUESTION','Is it certain that this corrective solution could be made operational to enable company activity to restart within a time delay sufficiently short to be acceptable to users?','09E03-03','09E03','2','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1659,'04','QUESTION','Have variants to the primary solution been considered in case the latter might encounter unforeseen difficulties?','09E03-04','09E03','2','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1660,'05','QUESTION','Is there a regular review of critical applications and corrective solutions envisaged?','09E03-05','09E03','2','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1661,'09','CATEGORY','Control of origin and receipt of data ','09F','09','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1662,'01','CATEGORY','Proof of origin, electronic signature ','09F01','09F','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1663,'01','QUESTION','Have sensitive transactions been identified which must be protected by electronic signature solutions implemented at the application level?','09F01-01','09F01','4','','','E2','10.1.1','12.3.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1664,'02','QUESTION','Is the conformity of signatures controlled automatically by the application?','09F01-02','09F01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1665,'03','QUESTION','Does the electronic signature solution offer valid and solid guarantees and has it been approved by the Information Security Officer?
The sufficient length of the key is one of among many parameters to take into consideration (as a function of the algorithm). The recommendation of an official organization can be a confidence factor.','09F01-03','09F01','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1666,'04','QUESTION','Do the procedure and mechanisms of storage, distribution and exchange of keys and more generally the management of the keys offer solid guarantees which merit confidence and are they approved by the Information Security Officer?','09F01-04','09F01','4','3','','E2','10.1.2','12.3.2'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1667,'05','QUESTION','Are the electronic signature mechanisms strictly protected against violation or change?
In the case of hardware solution or appliance, it should be physical protected against access to the signature mechanisms. If a software solution is used, it must itself contain an integrity control.','09F01-05','09F01','4','3','3','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1668,'06','QUESTION','Is shutdown or by-pass of the signature solution immediately detected and signaled to a team available 24 hrs a day or by direct call and capable of triggering an immediate reaction?','09F01-06','09F01','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1669,'07','QUESTION','Is there a procedure which details the operations to carry out in the case of error or alert?','09F01-07','09F01','3','','2','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1670,'08','QUESTION','Are electronic signature mechanisms, their parameters and associated procedures subject to regular audit?','09F01-08','09F01','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1671,'02','CATEGORY','Prevention of message duplication and replay (numbering, sequencing) ','09F02','09F','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1672,'01','QUESTION','Have sensitive transactions been identified which must be protected by sequencing control solutions implemented at the application level (or at the network level)?','09F02-01','09F02','4','','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1673,'02','QUESTION','Is the coherence of the numbers and sequences controlled automatically by the application or by the middleware used?','09F02-02','09F02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1674,'03','QUESTION','Does the numbering and sequencing  solution offer valid and solid guarantees and has it been approved by the Information Security Officer?
The recommendation of an official organization can be a confidence factor.','09F02-03','09F02','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1675,'04','QUESTION','Are the numbering and numbering control mechanisms strictly protected against violation or change?
In the case of hardware solution or appliance, it should be physical protected against access to the sequencing mechanisms. If a software solution is used, it must itself contain an integrity control.','09F02-04','09F02','4','3','3','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1676,'05','QUESTION','Is shutdown or by-pass of the numbering system immediately detected and signaled to a team available 24 hrs a day or by direct call and capable of triggering an immediate reaction?','09F02-05','09F02','4','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1677,'06','QUESTION','Is there a procedure which details the operations to carry out in the case of error or alert?','09F02-06','09F02','3','','2','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1678,'07','QUESTION','Are numbering mechanisms, their parameters and associated control procedures subject to regular audit?','09F02-07','09F02','4','3','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1679,'03','CATEGORY','Acknowledgments of receipt','09F03','09F','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1680,'01','QUESTION','Is there a procedure which requires an acknowledgment of receipt to be sent for all sensitive messages?
Note: in certain cases, checks may be based on the signature.','09F03-01','09F03','4','','','E1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1681,'02','QUESTION','Is an alert triggered when an acknowledgment of receipt is not sent (or received) for sensitive messages?','09F03-02','09F03','4','2','','E2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1682,'03','QUESTION','Is the acknowledgment of receipt emitted only after the message has been effectively considered by the target application?
No acknowledgment should be sent for a message still waiting for treatment ','09F03-03','09F03','4','3','','E3','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1683,'04','QUESTION','Is the acknowledgment of receipt mechanism protected against all undesirable intervention?','09F03-04','09F03','2','3','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1684,'05','QUESTION','Is there a procedure which details the operations to carry out in the case of error or alert?','09F03-05','09F03','3','2','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1685,'06','QUESTION','Is the acknowledgment of receipt system subject to regular audit?','09F03-06','09F03','3','2','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1686,'09','CATEGORY','Detection and management of application incident and anomalies ','09G','09','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1687,'01','CATEGORY','Detection of application anomalies','09G01','09G','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1688,'01','QUESTION','Have events or successions of events been analyzed which might reveal abnormal behavior or illicit action and, as a consequence, have specific monitoring points been identified?','09G01-01','09G01','4','','','E2','16.1.4',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1689,'02','QUESTION','Are features, detecting and recording sensitive events, installed in applications (with type of event, user identifier, date and time, etc.)?  ','09G01-02','09G01','4','','3','E2','12.6.1',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1690,'03','QUESTION','Is there an audit  trail within certain sensitive processes which records the events which would enable later diagnosis of anomalies?','09G01-03','09G01','4','','3','E3','16.1.4',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1691,'04','QUESTION','Are sensitive applications provided with an automatic monitoring function dealing in real time with large numbers of abnormal events (for example many unsuccessful connection attempts on user workstations or unsuccessful attempts to use sensitive transactions)?','09G01-04','09G01','4','','3','E3','16.1.4',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1692,'05','QUESTION','Are all these diagnostic elements registered?','09G01-05','09G01','2','','','E2','16.1.4',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1693,'06','QUESTION','Are there one or more applications capable of analyzing the individual anomaly diagnostic data and triggering an alert to operational personnel?','09G01-06','09G01','4','2','','E3','16.1.4',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1694,'07','QUESTION','Does the anomaly diagnostic system trigger an alarm in real time to a permanent surveillance team able or by direct call and able to react without delay?','09G01-07','09G01','4','','3','E3','16.1.4',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1695,'08','QUESTION','For each case of alert has the expected response from the intervention team been defined and is the availability of the intervention team sufficient to face this expectation?','09G01-08','09G01','4','','','E3','16.1.4',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1696,'09','QUESTION','Are the parameters defining the elements to record and the diagnostic analysis effected on these elements strictly protected (restricted access rights and strict authentication ) against illicit modification?','09G01-09','09G01','4','','','R2','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1697,'10','QUESTION','Does the stopping of the recording and record processing system trigger an alarm with the surveillance team?','09G01-10','09G01','4','','','R1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1698,'11','QUESTION','Are the procedures for recording, processing and diagnostic analysis and the availability of the intervention team regularly audited?','09G01-11','09G01','2','','','C1','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1699,'09','CATEGORY','Security of application services and transactions','09H','09','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1700,'01','CATEGORY','Securing application services on public networks
Information involved in application services passing over public networks should be protected from fraudulent activity, contract dispute and unauthorized disclosure and modification','09H01','09H','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1701,'01','QUESTION','Is the migration of existing services from private to public networks organized with the associated parties ?
Attention to the risk owners and all users should be prominent and the management requirements issues central to the decision','09H01-01','09H01','2','','','','14.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1702,'02','QUESTION','Have the security requirements specific to making information available on public networks been analyzed and thus defined the necessary protections and assurance?','09H01-02','09H01','2','','','E2','14.1.1','10.9.1'); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1703,'03','QUESTION','Have the classification levels for the information and services assets received a special attention?
The value of Personally Identifiable Information and strategic elements for the organization should be carefully established (see worksheets T1 to T3)','09H01-03','09H01','4','2','','','14.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1704,'04','QUESTION','Have Service level agreements for the permanence and continuity of the service been negotiated with the service providers ?
This is very important in the case of services obtained over the cloud and appropriate penalties should be clearly understood by the organization (e.g. in the case of interruption by the provider (error, accident, strike, bankruptcy, takeover, ...)) including the capacity to recover the proprietary data ','09H01-04','09H01','3','2','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1705,'05','QUESTION','Are the protection and verification of transactions appropriately managed?
Including payment information provided by the customer, integrity, confidentiality, protection against replay, confirmation of receipt, non-repudiation, etc. to guard against fraud.','09H01-05','09H01','3','2','','','14.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1706,'06','QUESTION','Are Service level agreements in place concerning the confidentiality of the information treated and/or stored by the service provider?
Means to control the agreements and to react rapidly should be guaranteed to the organization.','09H01-06','09H01','3','2','','','14.1.1',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1707,'07','QUESTION','Have protections to the security risks associated to web access been integrated to the application?
OWASP references 10 important threats like Injection flaws, cross site scripting and request forgery, broken sessions, insecure direct object references and cryptographic storage, security misconfiguration, failure to restrict URL access, insufficient transport layer protection, unvalidated redirects and forwards)','09H01-07','09H01','4','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1708,'08','QUESTION','Have the likelihood of attacks and threats been specifically analyzed for the application services?
Careful attention to  the level of the natural exposure settings in the worksheet Expo is required, firstly cyber attacks','09H01-08','09H01','3','','','','14.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1709,'09','QUESTION','Are the authentication, control of rights and logging mechanisms specifically enforced for administrative operations?','09H01-09','09H01','2','2','','','14.1.1',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1710,'10','QUESTION','Are the mutual levels of confidence (of each other`s identity, authorization, level of trust required in the integrity  and confidentiality of data exchanged) considered in regard of the requirements?
The quality of the security services 09A to 09G above should be appropriate with the requirements of the application service.','09H01-10','09H01','3','2','','','14.1.2',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1711,'11','QUESTION','Is there a regular review, at least once a year, of the application services and corrective solutions envisaged?
This review shall also consider shadow applications and data on public networks','09H01-11','09H01','2','2','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1712,'02','CATEGORY','Protecting application services transactions','09H02','09H','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1713,'01','QUESTION','Are specific security protection requirements defined and used for critical transactions attached to the application?
Compliance with legal and regulatory requirements is imperative.','09H02-01','09H02','3','','','','14.1.3',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1714,'02','QUESTION','Is the non disclosure of critical transactions protected by using strong cryptographic controls?
Secret authentication information of all parties should be valid and verified, communication paths between them are encrypted, protocols used are secured, storage of the transaction details are located in a protected environment.','09H02-02','09H02','3','','','','14.1.3',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1715,'03','QUESTION','Is the integrity of critical transactions protected by using electronic signatures?','09H02-03','09H02','4','','','','14.1.3',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1716,'04','QUESTION','Is the service of a trusted authority protected throughout the entire end-to-end certificate/signature management process?','09H02-04','09H02','3','','','','14.1.3',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1717,'05','QUESTION','Are administrators and users trained on their operations, rights and responsibilities and aware of the risks with networked applications?','09H02-05','09H02','3','2','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1718,'06','QUESTION','Is there a regular review, at least once a year, of the service transactions and corrective solutions envisaged?
This review shall also consider new threats and vulnerabilities on the applications and data on public networks','09H02-06','09H02','2','2','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1719,'03','CATEGORY','Electronic messaging','09H03','09H','','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1720,'01','QUESTION','Are there policies for the use of the various types of electronic messaging services, based on business security requirements?
Examples: email, social networking, electronic data interchange, instant messaging, file sharing ...','09H03-01','09H03','3','2','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1721,'02','QUESTION','Is an approval and authorization process, based on the policies, in place prior to using these services?','09H03-02','09H03','2','2','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1722,'03','QUESTION','Are stronger levels of authentication established for controlling access from publicly accessible networks?','09H03-03','09H03','3','','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1723,'04','QUESTION','Are the exchanges requiring protection commensurate with the classification scheme adopted by the organization?
Encryption, signature,authorized access, modification, denial of service, non repudiation.','09H03-04','09H03','3','2','','','',''); 
INSERT INTO ASSAUDIT_DEFAULT(`ID`,`IX`,`ATYPE`,`AVALUE`,`CATEGORY`,`PARENT`,`VW`,`VMAX`,`VMIN`,`VTYPE`,`VISO13`,`VISO5`) VALUES(1724,'05','QUESTION','Are administrators and users trained on the operations, rights and responsibilities and aware of the risks with electronic messaging?
Training  sessions and awareness messages should be regularly organized.','09H03-05','09H03','2','','','','',''); 
