SET MODE MYSQL;

DROP TABLE IF EXISTS `ROLE` CASCADE
;
DROP TABLE IF EXISTS `ASSPROCEDURE` CASCADE
;
DROP TABLE IF EXISTS `QUESTIONNAIRE_MODEL` CASCADE
;
DROP TABLE IF EXISTS `SECREQUIREMENT_SAFEGUARD` CASCADE
;
DROP TABLE IF EXISTS `SECREQUIREMENT_REFERENCE` CASCADE
;
DROP TABLE IF EXISTS `ASSAUDIT` CASCADE
;
DROP TABLE IF EXISTS `SERIOUSNESS` CASCADE
;
DROP TABLE IF EXISTS `ASSPROJECT` CASCADE
;
DROP TABLE IF EXISTS `ASSPROFILE_TEMPLATE` CASCADE
;
DROP TABLE IF EXISTS `ASSPROFILE` CASCADE
;
DROP TABLE IF EXISTS `ASSTEMPLATE` CASCADE
;
DROP TABLE IF EXISTS `SESTUSER_PSW` CASCADE
;
DROP TABLE IF EXISTS `SESTUSER` CASCADE
;
DROP TABLE IF EXISTS `REQUIREMENT` CASCADE
;
DROP TABLE IF EXISTS `SYSPARTICIPANT` CASCADE
;
DROP TABLE IF EXISTS `SYSPROJECT` CASCADE
;
DROP TABLE IF EXISTS `ASSET_MODEL` CASCADE
;
DROP TABLE IF EXISTS `VULNERABILITY_MODEL` CASCADE
;
DROP TABLE IF EXISTS `VULNERABILITY_REFERENCE` CASCADE
;
DROP TABLE IF EXISTS `VULNERABILITY_ASSET_REFERENCE` CASCADE
;
DROP TABLE IF EXISTS `RISK_MODEL` CASCADE
;
DROP TABLE IF EXISTS `THREAT_MODEL` CASCADE
;
DROP TABLE IF EXISTS `THREAT_REFERENCE` CASCADE
;
DROP TABLE IF EXISTS `RISK_SCENARIO_REFERENCE` CASCADE
;
DROP TABLE IF EXISTS `SAFEGUARD_MODEL` CASCADE
;
DROP TABLE IF EXISTS `STATUS_IMPACT` CASCADE
;
DROP TABLE IF EXISTS `STATUS_LIKELIHOOD` CASCADE
;
DROP TABLE IF EXISTS `RISKTREATMENT_MODEL` CASCADE
;
DROP TABLE IF EXISTS `SESTOBJ` CASCADE
;
DROP TABLE IF EXISTS `ASSAUDIT_DEFAULT` CASCADE
;


CREATE TABLE `SESTOBJ`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`IDENTIFIER` CHAR(36) NOT NULL UNIQUE,
	`OBJTYPE` varchar(20) NULL,
	CONSTRAINT `PK_SESTOBJ` PRIMARY KEY (`ID` ASC)
)

;
CREATE INDEX IX_SESTOBJ ON SESTOBJ (IDENTIFIER);

CREATE TABLE `SESTUSER`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`EMAIL` varchar(30) NULL UNIQUE,
	`NAME` varchar(20) NULL,
	`PASSWORD` varchar(20) NULL,
	`PROFILE` varchar(20) NULL,
	`SURNAME` varchar(20) NULL,
	`USERNAME` varchar(20) NULL UNIQUE,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,	
	CONSTRAINT `PK_User` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `SESTUSER_PSW`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`SESTUSER_ID` INT(10) NOT NULL,	
	`PASSWORD` varchar(20) NOT NULL,
	`UPD_TIME` datetime(6) NULL,	
	CONSTRAINT `PK_Sestuserpsw` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `ROLE`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`ROLE` varchar(20) NULL,
	`USER_ID` INT(10) NULL,	
	`PROJECT_ID` INT(10) NULL,
	CONSTRAINT `PK_Userrole` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `SYSPROJECT`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NULL,
	`DESCRIPTION` varchar(2000) NULL,
	`MANDATE` varchar(500) NULL,
	`PSCOPE` varchar(500) NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	CONSTRAINT `PK_Systemproject` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `SYSPARTICIPANT`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(20) NULL,
	`SURNAME` varchar(20) NULL,
	`ROLE` varchar(40) NULL,
	`SYSPROJECT_ID` INT(10) NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	CONSTRAINT `PK_Systemparticipant` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `ASSPROCEDURE`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(80) NOT NULL,
	`PHASE` varchar(20) NULL,	
	`CREATION_TIME` TIMESTAMP NULL,
	`UPDATE_TIME` TIMESTAMP NULL,
	`STATUS` varchar(20) NULL,
	`PROJECT_ID` INT(10) NOT NULL,
	`ASSET_ID` INT(10) NOT NULL,
	`THREAT_ID` INT(10) NOT NULL,
	`VULNERABILITY_ID` INT(10) NOT NULL,
	`SAFEGUARD_ID` INT(10) NOT NULL,
	`RISKMODEL_ID` INT(10) NOT NULL,
	`RISKTREATMENTMODEL_ID` INT(10) NOT NULL,
	`LASTUSERUPD_ID` INT(10) NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	CONSTRAINT `PK_Assessmentprocedure` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `ASSTEMPLATE`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(80) NULL UNIQUE,
	`DESCRIPTION` varchar(2000) NULL,
	`METHODOLOGY` varchar(20) NULL,	
	`PHASE` varchar(20) NULL,	
	`CREATION_TIME` TIMESTAMP NULL,	
	`ASSET_ID` INT(10) NOT NULL,
	`THREAT_ID` INT(10) NOT NULL,
	`VULNERABILITY_ID` INT(10) NOT NULL,
	`SAFEGUARD_ID` INT(10) NOT NULL,
	`RISKMODEL_ID` INT(10) NOT NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	CONSTRAINT `PK_Assessmenttemplate` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `ASSPROFILE`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NULL,
	`DESCRIPTION` varchar(2000) NULL,
	`ORGANIZATION` varchar(100) NULL,
	`PHASE` varchar(20) NULL,
	`CREATION_TIME` TIMESTAMP NULL,
	`UPDATE_TIME` TIMESTAMP NULL,
	`METHODOLOGY` varchar(20) NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	CONSTRAINT `PK_Assessmentprofile` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `ASSPROFILE_TEMPLATE`
(
	`PROFILE_ID` INT(10) NOT NULL,
	`TEMPLATE_ID` INT(10) NOT NULL,
	CONSTRAINT `U_ASSPROFILE_TEMPLATE` UNIQUE (`PROFILE_ID`,`TEMPLATE_ID`)
)

;

CREATE TABLE `ASSPROJECT`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(50) NULL UNIQUE,
	`DESCRIPTION` varchar(2000) NULL,
	`METHODOLOGY` varchar(20) NULL,
	`CREATION_TIME` TIMESTAMP NULL,
	`UPDATE_TIME` TIMESTAMP NULL,
	`STATUS` varchar(20) NULL,
	`SYSPROJECT_ID` INT(10) NOT NULL,
	`USERPM` INT(10) NOT NULL,
	`TEMPLATE_ID` INT(10) NOT NULL,
	`PROFILE_ID` INT(10) NOT NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	CONSTRAINT `PK_Assessmentproject` PRIMARY KEY (`ID` ASC)
)
	
;

CREATE TABLE `ASSAUDIT`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`ATYPE` varchar(300) NULL,
	`PROJECT_ID` INT(10) NOT NULL,
	`PROFILE_ID` INT(10) NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	CONSTRAINT `PK_Audit` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `QUESTIONNAIRE_MODEL`
(  
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`IX` INT(2) NULL,
	`AUDIT_ID` INT(10) NOT NULL,
	`CATEGORY` varchar(30) NULL,
	`QTYPE` varchar(300) NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL,
	`QUESTIONNAIRE_MODEL_JSON` LONGTEXT NOT NULL,
	CONSTRAINT `PK_Questionnaire` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `ASSAUDIT_DEFAULT`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`IX` varchar(2) NOT NULL,
	`AVALUE` varchar(2000) NOT NULL,	
	`ATYPE` varchar(300) NULL,
	`CATEGORY` varchar(30) NULL,
	`PARENT` varchar(30) NULL,
	`VW` varchar(10) NULL,
	`VMAX` varchar(10) NULL,
	`VMIN` varchar(10) NULL,
	`VTYPE` varchar(10) NULL,
	`VISO13` varchar(30) NULL,
	`VISO5` varchar(30) NULL,
	`QUESTIONNAIRE_JSON` LONGTEXT NULL,
	CONSTRAINT `PK_Default` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `REQUIREMENT`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`AUTHOR` varchar(30) NULL,
	`CATEGORY` varchar(100) NULL,
	`PARENT` INT(10) NULL,
	`DESCRIPTION` varchar(4000) NULL,
	`ELEMENT_TYPE` varchar(10) NULL,
	`REQ_ID` varchar(30) NOT NULL,
	`LASTUPD` varchar(30) NULL,
	`NOTE` varchar(2000) NULL,
	`SOURCE` varchar(10) NULL,
	`SOURCE_DESCRIPTION` varchar(1000) NULL,
	`STABILITY` varchar(10) NULL,
	`STATUS` varchar(10) NULL,
	`SUBCATEGORY` varchar(30) NULL,
	`TAG` varchar(30) NULL,
	`TITLE` varchar(30) NULL,
	`TYPOLOGY` varchar(15) NULL,
	`VERSION` varchar(10) NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	`SYSPROJECT_ID` INT(10) NULL,	
        `PRIORITY` varchar(10) NULL,
	CONSTRAINT `PK_Requirement` PRIMARY KEY (`ID` ASC)
)

;
CREATE UNIQUE INDEX sysrequirement_prj_file ON `REQUIREMENT` (`REQ_ID`, `CATEGORY`, `SYSPROJECT_ID`);

CREATE TABLE `SECREQUIREMENT_REFERENCE`
(
    `ID` INT(10) NOT NULL AUTO_INCREMENT,
	`AUTHOR` varchar(30) NULL,
	`CATEGORY` varchar(30) NULL,
	`PARENT` INT(10) NULL,
	`DESCRIPTION` varchar(4000) NULL,
	`ELEMENT_TYPE` varchar(10) NULL,
	`REQ_ID` varchar(30) UNIQUE NOT NULL,
	`LASTUPD` varchar(30) NULL,
	`NOTE` varchar(8000) NULL,
	`SOURCE` varchar(10) NULL,
	`SOURCE_DESCRIPTION` varchar(1000) NULL,
	`STABILITY` varchar(10) NULL,
	`STATUS` varchar(10) NULL,
	`SUBCATEGORY` varchar(30) NULL,
	`TAG` varchar(30) NULL,
	`TITLE` varchar(1000) NULL,
	`TYPOLOGY` varchar(15) NULL,
	`VERSION` varchar(10) NULL,
	`SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	`SYSPROJECT_ID` INT(10) NULL,	
    `PRIORITY` varchar(10) NULL,	
    `SCORE` varchar(10) NULL,
	CONSTRAINT `PK_SECREQUIREMENT` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `SECREQUIREMENT_SAFEGUARD`
(
	`SECREQUIREMENT_ID` INT(10) NOT NULL,
	`SAFEGUARD_REFERENCE_ID` INT(10) NOT NULL,
	`CONTRIBUTION` int(10) NOT NULL,
	CONSTRAINT `U_SECREQ_SAFEGUARD` UNIQUE (`SECREQUIREMENT_ID`,`SAFEGUARD_REFERENCE_ID`)
)

;

CREATE TABLE `ASSET_MODEL`
(
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`ASSET_MODEL_JSON` LONGTEXT NOT NULL,
    `SESTOBJ_ID` CHAR(36) NOT NULL UNIQUE,
	CONSTRAINT `PK_AssetModel` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `VULNERABILITY_MODEL`
(
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`VULNERABILITY_MODEL_JSON` LONGTEXT NOT NULL,
    `SESTOBJ_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_VulnerabilityModel` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `VULNERABILITY_REFERENCE`
(
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`CATALOGUE` varchar(20) NULL,
	`CATALOGUE_ID` varchar(40) NULL,
	`UPDATE_TIME` TIMESTAMP NULL,
	`NAME` varchar(40) NULL,
	`DAMAGE` varchar(40) NULL,
	`PHASE` varchar(20) NULL,
	`EXPLOITABILITY` varchar(20) NULL,
	`SCORE` varchar(20) NULL,
	`SCORING_TYPE` varchar(20) NULL,
	`VULNERABILITY_JSON` LONGTEXT NOT NULL,
    `SESTOBJ_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_VulnerabilityReference` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `VULNERABILITY_ASSET_REFERENCE`
(
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`SECONDARY_ASSET_CATEGORY` varchar(100) NULL,
    `SESTOBJ_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_VulnerabilityAssetReference` PRIMARY KEY (`ID` ASC)
)
;

CREATE TABLE `RISK_MODEL`
(
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`RISK_MODEL_JSON` LONGTEXT NOT NULL,
    `SESTOBJ_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_RiskModel` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `THREAT_MODEL`
(
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`THREAT_MODEL_JSON` LONGTEXT NOT NULL,
    `SESTOBJ_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_ThreatModel` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `SAFEGUARD_MODEL`
(
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`SAFEGUARD_MODEL_JSON` LONGTEXT NOT NULL,
    `SESTOBJ_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_SafeguardModel` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `SERIOUSNESS`
(
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`PROJECT_ID` INT(10) NULL,
	`PROFILE_ID` INT(10) NULL,
    `IMPACT` INT(2) NOT NULL,
    `LIKELIHOOD` INT(2) NOT NULL,
    `SERIOUSNESS` INT(2) NOT NULL,
	CONSTRAINT `PK_Seriousness` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `STATUS_IMPACT` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` int(10) DEFAULT NULL,
  `PROFILE_ID` int(10) DEFAULT NULL,
  `INTRINSIC_IMPACT` int(2) NOT NULL,
  `SECURITY_IMPACT` VARCHAR(20) NOT NULL,
  `CONFINING` int(2) NOT NULL,
  `PALLIATION` int(2) NOT NULL,
  `CALCULATED_IMPACT` int(2) NOT NULL,
  CONSTRAINT `PK_Status_Impact` PRIMARY KEY (`ID` ASC)
);




CREATE TABLE `STATUS_LIKELIHOOD` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` int(10) DEFAULT NULL,
  `PROFILE_ID` int(10) DEFAULT NULL,
  `INTRINSIC_LIKELIHOOD` int(2) NOT NULL,
  `CLASS` VARCHAR(20) NOT NULL,
  `DISSUASION` int(2) NOT NULL,
  `PREVENTION` int(2) NOT NULL,
  `CALCULATED_LIKELIHOOD` int(2) NOT NULL,
  CONSTRAINT `PK_Status_Likelihood` PRIMARY KEY (`ID` ASC)
);

CREATE TABLE `THREAT_REFERENCE` (
  `ID` 	INT(10) NOT NULL AUTO_INCREMENT,
  `CATALOGUE` VARCHAR(20) DEFAULT NULL,
  `CATALOGUE_ID` VARCHAR(40) DEFAULT NULL,
  `UPDATE_TIME` TIMESTAMP NULL DEFAULT NULL,
  `NAME` VARCHAR(400) DEFAULT NULL,
  `PHASE` VARCHAR(20) DEFAULT NULL,
  `LIKELIHOOD` VARCHAR(20) DEFAULT NULL,
  `SCORE` VARCHAR(20) DEFAULT NULL,
  `THREATCLASS` VARCHAR(20) DEFAULT NULL,
  `THREAT_JSON` longtext NOT NULL,
  `SESTOBJ_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_ThreatReference` PRIMARY KEY (`ID` ASC)
)

;

CREATE TABLE `RISK_SCENARIO_REFERENCE` (
  `ID` 	INT(10) NOT NULL AUTO_INCREMENT,
  `ASSET_TYPE` VARCHAR(100) DEFAULT NULL,
  `SECONDARY_ASSET_TYPE` VARCHAR(100) DEFAULT NULL,
  `SECURITY_SCOPE` VARCHAR(20) DEFAULT NULL,
  `VULNERABILITY_REFERENCE`  INT(10)  DEFAULT NULL,
  `THREAT_REFERENCE` INT(10) DEFAULT NULL,
  `DISSUASION` VARCHAR(120) DEFAULT NULL,
  `PREVENTION` VARCHAR(120) DEFAULT NULL,
  `CONFINING` VARCHAR(120) DEFAULT NULL,
  `PALLIATIVE` VARCHAR(120) DEFAULT NULL,
  `SESTOBJ_ID` CHAR(36) NULL,
	CONSTRAINT `PK_RiskScenarioReference` PRIMARY KEY (`ID` ASC)
)

;


CREATE TABLE `RISKTREATMENT_MODEL`
(
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`RISKTREATMENT_MODEL_JSON` LONGTEXT NOT NULL,
    `SESTOBJ_ID` CHAR(36) NOT NULL,
	CONSTRAINT `PK_RiskTreatmentModel` PRIMARY KEY (`ID` ASC)
)

;
ALTER TABLE `SYSPARTICIPANT` 
 ADD CONSTRAINT `FK_SYSPARTICIPANT_PROJECT`
	FOREIGN KEY (`SYSPROJECT_ID`) REFERENCES `SYSPROJECT` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `SYSPARTICIPANT` 
 ADD CONSTRAINT `FK_SYSPARTICIPANT_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SYSPROJECT` 
 ADD CONSTRAINT `FK_SYSPROJECT_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSPROCEDURE` 
 ADD CONSTRAINT `FK_ASSPROCEDURE_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSPROCEDURE` 
 ADD CONSTRAINT `FK_ASSPROCEDURE_PROJECT`
	FOREIGN KEY (`PROJECT_ID`) REFERENCES `ASSPROJECT` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ASSPROCEDURE` 
 ADD CONSTRAINT `FK_ASSPROCEDURE_ASSETMODEL`
	FOREIGN KEY (`ASSET_ID`) REFERENCES `ASSET_MODEL` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ASSPROCEDURE` 
 ADD CONSTRAINT `FK_ASSPROCEDURE_VULNERABILITYMODEL`
	FOREIGN KEY (`VULNERABILITY_ID`) REFERENCES `VULNERABILITY_MODEL` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ASSPROCEDURE` 
 ADD CONSTRAINT `FK_ASSPROCEDURE_THREATMODEL`
	FOREIGN KEY (`THREAT_ID`) REFERENCES `THREAT_MODEL` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ASSPROCEDURE`
 ADD CONSTRAINT `FK_ASSPROCEDURE_NAME_UNIQUE`
	UNIQUE (`PROJECT_ID`,`NAME`)
;

ALTER TABLE `ASSTEMPLATE` 
 ADD CONSTRAINT `FK_ASSTEMPLATE_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSTEMPLATE` 
 ADD CONSTRAINT `FK_ASSTEMPLATE_ASSETMODEL`
	FOREIGN KEY (`ASSET_ID`) REFERENCES `ASSET_MODEL` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ASSTEMPLATE` 
 ADD CONSTRAINT `FK_ASSTEMPLATE_VULNERABILITYMODEL`
	FOREIGN KEY (`VULNERABILITY_ID`) REFERENCES `VULNERABILITY_MODEL` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ASSTEMPLATE` 
 ADD CONSTRAINT `FK_ASSTEMPLATE_THREATMODEL`
	FOREIGN KEY (`THREAT_ID`) REFERENCES `THREAT_MODEL` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ASSPROFILE` 
 ADD CONSTRAINT `FK_ASSPROFILE_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSPROFILE_TEMPLATE` 
 ADD CONSTRAINT `FK_ASSPROFILE_TEMPLATE_PROFILE`
	FOREIGN KEY (`PROFILE_ID`) REFERENCES `ASSPROFILE` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ASSPROFILE_TEMPLATE` 
 ADD CONSTRAINT `FK_ASSPROFILE_TEMPLATE_TEMPLATE`
	FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `ASSTEMPLATE` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ASSPROJECT` 
 ADD CONSTRAINT `FK_ASSPROJECT_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSPROJECT` 
 ADD CONSTRAINT `FK_ASSPROJECT_SYSPROJECT`
	FOREIGN KEY (`SYSPROJECT_ID`) REFERENCES `SYSPROJECT` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSPROJECT` 
 ADD CONSTRAINT `FK_ASSPROJECT_USERPM`
	FOREIGN KEY (`USERPM`) REFERENCES `SESTUSER` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSPROJECT` 
 ADD CONSTRAINT `FK_ASSPROJECT_TEMPLATE`
	FOREIGN KEY (`TEMPLATE_ID`) REFERENCES `ASSTEMPLATE` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSPROJECT` 
 ADD CONSTRAINT `FK_ASSPROJECT_PROFILE`
	FOREIGN KEY (`PROFILE_ID`) REFERENCES `ASSPROFILE` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SESTUSER` 
 ADD CONSTRAINT `FK_USER_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SESTUSER_PSW` 
 ADD CONSTRAINT `FK_USERPSW_USER`
	FOREIGN KEY (`SESTUSER_ID`) REFERENCES `SESTUSER` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ROLE` 
 ADD CONSTRAINT `FK_ROLE_USER_ID`
	FOREIGN KEY (`USER_ID`) REFERENCES `SESTUSER` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `ROLE` 
 ADD CONSTRAINT `FK_ROLE_PROJECT`
	FOREIGN KEY (`PROJECT_ID`) REFERENCES `ASSPROJECT` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;


ALTER TABLE `ASSAUDIT` 
 ADD CONSTRAINT `FK_ASSAUDIT_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSAUDIT` 
 ADD CONSTRAINT `FK_ASSAUDIT_PROFILE`
	FOREIGN KEY (`PROFILE_ID`) REFERENCES `ASSPROFILE` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSAUDIT` 
 ADD CONSTRAINT `FK_ASSAUDIT_PROJECT`
	FOREIGN KEY (`PROJECT_ID`) REFERENCES `ASSPROJECT` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `QUESTIONNAIRE_MODEL` 
 ADD CONSTRAINT `FK_QUESTIONNAIREM_AUDIT`
	FOREIGN KEY (`AUDIT_ID`) REFERENCES `ASSAUDIT` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `REQUIREMENT` 
 ADD CONSTRAINT `FK_SYSPROJECT`
	FOREIGN KEY (`SYSPROJECT_ID`) REFERENCES `SYSPROJECT` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `REQUIREMENT` 
 ADD CONSTRAINT `FK_PARENT`
	FOREIGN KEY (`PARENT`) REFERENCES `REQUIREMENT` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SECREQUIREMENT_REFERENCE` 
 ADD CONSTRAINT `FK_SECREQ_PARENT`
	FOREIGN KEY (`PARENT`) REFERENCES `SECREQUIREMENT_REFERENCE` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `SECREQUIREMENT_REFERENCE` 
 ADD CONSTRAINT `FK_SECREQ_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SECREQUIREMENT_SAFEGUARD` 
 ADD CONSTRAINT `FK_SAFEGUARD_SECREQUIREMENT_ID`
	FOREIGN KEY (`SECREQUIREMENT_ID`) REFERENCES `SECREQUIREMENT_REFERENCE` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SECREQUIREMENT_SAFEGUARD` 
 ADD CONSTRAINT `FK_SAFEGUARD_REFERENCE_ID`
	FOREIGN KEY (`SAFEGUARD_REFERENCE_ID`) REFERENCES `ASSAUDIT_DEFAULT` (`ID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ASSET_MODEL` 
 ADD CONSTRAINT `FK_ASSETMODEL_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `VULNERABILITY_MODEL` 
 ADD CONSTRAINT `FK_VULNERABILITYMODEL_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `RISK_MODEL` 
 ADD CONSTRAINT `FK_RISKMODEL_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `THREAT_MODEL` 
 ADD CONSTRAINT `FK_THREAT_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SAFEGUARD_MODEL` 
 ADD CONSTRAINT `FK_SAFEGUARD_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `VULNERABILITY_REFERENCE` 
 ADD CONSTRAINT `FK_VULNERABILITYREFERENCE_SESTOBJ`
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `THREAT_REFERENCE`
  ADD CONSTRAINT `FK_THREATREFERENCE_SESTOBJ` 
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE `RISKTREATMENT_MODEL`
  ADD CONSTRAINT `FK_RISKTREATMENT_SESTOBJ` 
	FOREIGN KEY (`SESTOBJ_ID`) REFERENCES `SESTOBJ` (`IDENTIFIER`) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE `RISK_SCENARIO_REFERENCE`
 ADD CONSTRAINT `FK_RISK_SCENARIO_VULNERABILITY`
	FOREIGN KEY (`VULNERABILITY_REFERENCE`) REFERENCES `VULNERABILITY_REFERENCE` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE `RISK_SCENARIO_REFERENCE`
 ADD CONSTRAINT `FK_RISK_SCENARIO_THREAT`
	FOREIGN KEY (`THREAT_REFERENCE`) REFERENCES `THREAT_REFERENCE` (`ID`) ON DELETE CASCADE ON UPDATE No Action
;

ALTER TABLE SESTOBJ ADD COLUMN LOCKED_BY CHAR(36);
